---
title: "Get Started"
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

This package contains aggregated and policy-level datasets. Below a list by country
or region is given.


-  Australia:
    
     -  [`auscathist`](https://dutangc.github.io/CASdatasets/reference/auscathist.html): Historical disaster statistics in Australia.
     -  [`ausNLHYCapAdeq`](https://dutangc.github.io/CASdatasets/reference/ausNLHYtotal.html),
              [`ausNLHYFinPerf`](https://dutangc.github.io/CASdatasets/reference/ausNLHYtotal.html), [`ausNLHYFinPos`](https://dutangc.github.io/CASdatasets/reference/ausNLHYtotal.html),
              [`ausNLHYLiability`](https://dutangc.github.io/CASdatasets/reference/ausNLHYtotal.html),    [`ausNLHYOffProf`](https://dutangc.github.io/CASdatasets/reference/ausNLHYtotal.html),
              [`ausNLHYOpIncExp`](https://dutangc.github.io/CASdatasets/reference/ausNLHYtotal.html), [`ausNLHYPremClaim`](https://dutangc.github.io/CASdatasets/reference/ausNLHYtotal.html),
              [`ausNLHYPrivInsur`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html), [`ausNLHYPubInsur`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html),
            [`ausNLHYRecAASB`](https://dutangc.github.io/CASdatasets/reference/ausNLHYtotal.html), [`ausNLHYReserve`](https://dutangc.github.io/CASdatasets/reference/ausNLHYtotal.html): Australian Market - non-life insurance (aggregate level).
     -  [`ausNLHYCapAdeqByComp`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html), [`ausNLHYClaimByState`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html),
              [`ausNLHYFinPerfByComp`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html), [`ausNLHYFinPerfPublic`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html),
              [`ausNLHYFinPosByComp`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html), [`ausNLHYFinPosPublic`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html),
              [`ausNLHYOpIncExpPublic`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html), [`ausNLHYPremByState`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html),
              [`ausNLHYPremClaimPublic`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html), [`ausNLHYPrivInsur`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html),
            [`ausNLHYPubInsur`](https://dutangc.github.io/CASdatasets/reference/ausNLHYby.html): Australian Market - non-life insurance (company, state, public level).
     -  [`ausNLHYLloydAsset`](https://dutangc.github.io/CASdatasets/reference/ausNLHYlloyds.html), [`ausNLHYLloydGPI`](https://dutangc.github.io/CASdatasets/reference/ausNLHYlloyds.html)
            [`ausNLHYLloydUWAcc`](https://dutangc.github.io/CASdatasets/reference/ausNLHYlloyds.html), [`ausNLHYLloydUWRes`](https://dutangc.github.io/CASdatasets/reference/ausNLHYlloyds.html): Lloyds Market in Australia.
     - [`austri1autoBI7895`](https://dutangc.github.io/CASdatasets/reference/austriLob.html), [`austri2auto`](https://dutangc.github.io/CASdatasets/reference/austriLob.html): Australian claim triangles.
     - [`ausprivautolong`](https://dutangc.github.io/CASdatasets/reference/ausprivauto.html), [`ausMTPL8486`](https://dutangc.github.io/CASdatasets/reference/ausprivauto.html),
        [`ausprivauto0405`](https://dutangc.github.io/CASdatasets/reference/ausprivauto.html): Australian private motor datasets (by policy).
     - [`ausNSWdriver04`](https://dutangc.github.io/CASdatasets/reference/ausNSW.html), [`ausNSWdeath02`](https://dutangc.github.io/CASdatasets/reference/ausNSW.html): New South Wales statistics.
        

-  Belgium:
    
     - [`beaonre`](https://dutangc.github.io/CASdatasets/reference/beaonre.html): AON Re Belgium dataset.
     - [`beMTPL16`](https://dutangc.github.io/CASdatasets/reference/beMTPL16.html): a MTPL Belgium dataset of 2016 (by policy).
     - [`beMTPL97`](https://dutangc.github.io/CASdatasets/reference/beMTPL97.html): a MTPL Belgium dataset of 1997 (by policy).
     - [`besecura`](https://dutangc.github.io/CASdatasets/reference/besecura.html): Secura Re Belgium dataset.
        
-  Brazil:
  
     - [`brgeomunicins`](https://dutangc.github.io/CASdatasets/reference/brgeomunicins.html): a dataset of Brazilian cities with
            insurance indicators (exposure, claim frequency and premium).
            Geographical datasets `brgeomunic_sf, `brgeomunic_sp` should
            be downloaded from the github repository in extra directory `geodata.
     - [`brautocoll`](https://dutangc.github.io/CASdatasets/reference/brautocoll.html): a Brazilian dataset of auto collision in Belo
            Horizonte during one month (categorical claim severity).
     - [`braggprem`](https://dutangc.github.io/CASdatasets/reference/braggclaimprem.html), [`braggclaim`](https://dutangc.github.io/CASdatasets/reference/braggclaimprem.html): aggregate Brazilian datasets per region.
     - [`brvehins1`](https://dutangc.github.io/CASdatasets/reference/brvehins.html): a Brazilian vehicle insurance datasets
            (by policy) with risk features except City code.
     - [`brvehins2`](https://dutangc.github.io/CASdatasets/reference/brvehins.html): a Brazilian vehicle insurance datasets
            (by policy) with risk features including City code.
    

-  Canada:
    
     - [`canlifins`](https://dutangc.github.io/CASdatasets/reference/canlifins.html), [`canlifins2`](https://dutangc.github.io/CASdatasets/reference/canlifins.html): A portfolio of a Canadian life insurer.
     - [`catelematic13`](https://dutangc.github.io/CASdatasets/reference/catelematic13.html): Canadian telematic insurance dataset.
    
-  Danemark: 
    
     - [`danishuni`](https://dutangc.github.io/CASdatasets/reference/danish.html), [`danishmulti`](https://dutangc.github.io/CASdatasets/reference/danish.html): Danish reinsurance claim dataset.
    
-  European Union: 
    
     - [`eudirectlapse`](https://dutangc.github.io/CASdatasets/reference/eudirectlapse.html): non-life insurance lapse dataset.
     - [`euhealthinsurance`](https://dutangc.github.io/CASdatasets/reference/euhealthinsurance.html): European health insurance dataset.
     - [`euMTPL`](https://dutangc.github.io/CASdatasets/reference/euMTPL.html): European motor TPL insurance dataset.
    
-  France:
    
     - [`freaggnumber`](https://dutangc.github.io/CASdatasets/reference/freaggnumber.html): a French aggregate claim number dataset.
     - [`frebiloss`](https://dutangc.github.io/CASdatasets/reference/frebiloss.html): French business interruption losses.
     - [`freclaimset`](https://dutangc.github.io/CASdatasets/reference/freclaimset.html), freclaimset2: French claim settlements.

     - [`frecomfire`](https://dutangc.github.io/CASdatasets/reference/frecomfire.html): French commercial fire losses.
     - [`freDisTables`](https://dutangc.github.io/CASdatasets/reference/fredistables.html): French disability tables.
     - [`fremarine`](https://dutangc.github.io/CASdatasets/reference/fremarine.html): French marine claim dataset (by policy).
     - [`freMortTables`](https://dutangc.github.io/CASdatasets/reference/fremorttables.html): French mortality tables.
     - [`fremotorclaim`](https://dutangc.github.io/CASdatasets/reference/fremotorclaim.html): French private motor claim datasets (by policy).
     - [`freMTPL`](https://dutangc.github.io/CASdatasets/reference/freMTPL.html): two French Motor-TPL claim datasets (by policy).
     - [`freMPL`](https://dutangc.github.io/CASdatasets/reference/freMPL.html): a collection of ten French Motor personal line datasets (by policy).
     - [`freportfolio`](https://dutangc.github.io/CASdatasets/reference/freportfolio.html): fictive mortality tables and French
        nation-wide corresponding tables; two disability datasets from a French insurer.
     - [`fre4LoBtriangles`](https://dutangc.github.io/CASdatasets/reference/fre4triLob.html): A collection of triangles 
        line of business from a private insurer.
     - [`pricingame`](https://dutangc.github.io/CASdatasets/reference/pricingame.html): Datesets used at Pricing Games of the
    French Institute of Actuaries.`    
    
-  Germany:
    
     - [`credit`](https://dutangc.github.io/CASdatasets/reference/credit.html): A German Credit dataset.    
    
-  Italy:
    
     - [`itamtplcost`](https://dutangc.github.io/CASdatasets/reference/itamtplcost.html): Large losses of an Italian Motor-TPL company.
    
-  New Zealand:
  
     -  [`nzcathist`](https://dutangc.github.io/CASdatasets/reference/nzcathist.html): Historical disaster statistics in New Zealand.
    

-  Norway:
    
     - [`norauto`](https://dutangc.github.io/CASdatasets/reference/norauto.html): Norwegian automobile dataset.
     - [`norfire`](https://dutangc.github.io/CASdatasets/reference/norfire.html): Norwegian fire dataset.
     - [`Norberg`](https://dutangc.github.io/CASdatasets/reference/Norberg.html): Norberg's credibility dataset.
     - [`nortritpl8800`](https://dutangc.github.io/CASdatasets/reference/nortritpl.html): Norwegian claim triangle.
    
-  Singapore:
    
     - [`sgautonb`](https://dutangc.github.io/CASdatasets/reference/sgautonb.html): Singapore Automobile claim count dataset.
     - sgtriangles: Singapore Property and Casualty triangles.
    
-  Sweden:
    
     - [`swautoins`](https://dutangc.github.io/CASdatasets/reference/swautoins.html): Swedish Motor Insurance dataset
     - [`swbusscase`](https://dutangc.github.io/CASdatasets/reference/swbuss.html): Swedish Buss Insurance dataset
     - [`swmotorcycle`](https://dutangc.github.io/CASdatasets/reference/swmotorcycle.html): Swedish Motorcycle Insurance dataset
    
-  United Kingdom:
    
     - [`ukaggclaim`](https://dutangc.github.io/CASdatasets/reference/ukaggclaim.html): United Kingdom Car Insurance Claims.
     - [`ukautocoll`](https://dutangc.github.io/CASdatasets/reference/ukautocoll.html): United Kingdom Car Collision Insurance Claims.
    
-  United States of America:
    
     - [`Davis`](https://dutangc.github.io/CASdatasets/reference/Davis.html): Davis height-weight dataset.
     - [`ICB1`](https://dutangc.github.io/CASdatasets/reference/ICB.html), [`ICB2`](https://dutangc.github.io/CASdatasets/reference/ICB.html): Insurance Company Benchmarks.
     - [`lossalae`](https://dutangc.github.io/CASdatasets/reference/lossalae.html),[`lossalaefull`](https://dutangc.github.io/CASdatasets/reference/lossalae.html): General Third Part-liability claims and expenses.
     - [`SOAGMI`](https://dutangc.github.io/CASdatasets/reference/SOAGMI.html): SOA Group Medical Insurance dataset.

     - [`usautoBI`](https://dutangc.github.io/CASdatasets/reference/usautoBI.html): Automobile Bodily Injuries in US.
     - [`usautotriangles`](https://dutangc.github.io/CASdatasets/reference/usautotri.html): US automobile triangles.
     - [`usexpense`](https://dutangc.github.io/CASdatasets/reference/usexpense.html): US expense dataset.
     - [`usGLtriangles`](https://dutangc.github.io/CASdatasets/reference/usGLtriangles.html): US Property and Casualty triangles.
     - [`ushurricane`](https://dutangc.github.io/CASdatasets/reference/ushurricane.html), [`ushustormloss4980`](https://dutangc.github.io/CASdatasets/reference/ushurricanesub.html):
            Historical hurricane statistics in United States of America.
     - [`uslapseagent`](https://dutangc.github.io/CASdatasets/reference/uslapseagent.html): US lapse dataset from tied-agent channel.
     - [`usmassBI`](https://dutangc.github.io/CASdatasets/reference/usmassBI.html): US Massachusetts Automobile bodily injury claim datasets.
     - [`usmedclaim`](https://dutangc.github.io/CASdatasets/reference/usmedclaim.html): US medical claim triangle.
     - [`usMSHA1316`](https://dutangc.github.io/CASdatasets/reference/usMSHA1316.html): US Mine Safety and Health Administration claim dataset.
     - [`usMVTA`](https://dutangc.github.io/CASdatasets/reference/usMVTA.html): US motor vehicle traffic accident.
     - [`usprivautoclaim`](https://dutangc.github.io/CASdatasets/reference/usprivautoclaim.html): private automobile claims.
     - [`usquakeLR`](https://dutangc.github.io/CASdatasets/reference/usearthquake.html): California earthquake loss ratios.
     - [`ustermlife`](https://dutangc.github.io/CASdatasets/reference/ustermlife.html): Term life insurance survey.
     - [`uswarrantaggnum`](https://dutangc.github.io/CASdatasets/reference/uswarrantaggnum.html): US warranty automobile.
     - [`usworkcomp`](https://dutangc.github.io/CASdatasets/reference/usworkerscomp.html): US workers compensation datasets.
    
-  Misc.:     
    
     - [`eqlist`](https://dutangc.github.io/CASdatasets/reference/eqlist.html): Earthquake list.
     - [`hurricanehist`](https://dutangc.github.io/CASdatasets/reference/hurricanehist.html): Hurricane history.
     - [`PnCdemand`](https://dutangc.github.io/CASdatasets/reference/PnCdemand.html): Property and Casualty demand.
     - [`spacedata`](https://dutangc.github.io/CASdatasets/reference/spacedata.html): Space dataset.
     - [`ECBYieldCurve`](https://dutangc.github.io/CASdatasets/reference/ECBYieldCurve.html), [`FedYieldCurve`](https://dutangc.github.io/CASdatasets/reference/FedYieldCurve.html) Yield curve
            for eurozone and US.
     - [`forexUSUK`](https://dutangc.github.io/CASdatasets/reference/forex.html) Foreign exchange rate between USD and GBP.
     - Use the HMD website for mortality tables https://www.mortality.org/.
    
    


Here is a list of datasets whose name has changed compared to the book 'Computational Actuarial Science with R':'
  
- Chapter 1: `extreme2datasince1899` is [`hurricanehist`](https://dutangc.github.io/CASdatasets/reference/hurricanehist.html).
- Chapter 5: `accidents` and `accidents_data` are 
      merged in [`brautocoll`](https://dutangc.github.io/CASdatasets/reference/brautocoll.html); `55mu2500gsd` is `brgeomunic_sf` in 
      extra directory `geodata` in the github repository;
      `sul_sp` is stored in [`brgeomunicins`](https://dutangc.github.io/CASdatasets/reference/brgeomunicins.html).
- Chapter 9: `MyPortfolio` is [`freprojqxINSEE`](https://dutangc.github.io/CASdatasets/reference/freportfolio.html).
- Chapter 10: `DataMortality` is [`freptfpermdis`](https://dutangc.github.io/CASdatasets/reference/freportfolio.html).
- Chapter 11: `DEXUSUK` is [`forexUSUK`](https://dutangc.github.io/CASdatasets/reference/forex.html).
- Chapter 14: `CONTRACTS` is [`freMTPLfreq`](https://dutangc.github.io/CASdatasets/reference/freMTPL.html); `CLAIMS` is [`freMTPLsev`](https://dutangc.github.io/CASdatasets/reference/freMTPL.html).
- Chapter 15: `AutoClaimData` is [`usmassBI2`](https://dutangc.github.io/CASdatasets/reference/usmassBI.html).
  


