---
title: "CASdatasets usage in research articles and books"
date: '`r Sys.Date()`'
date-format: "MMMM, YYYY"
author: "Christophe Dutang"
categories: [Claim severity, Claim frequency, Risk measure, Pricing, Extreme value analysis, Multivariate and copula models, Bayesian analysis]
vignette: >
  %\VignetteIndexEntry{CASdatasets usage}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---



This vignette lists the published papers or books using datasets of `CASdatasets` package. References are ordered chronologically.



# General usage and/or review papers


<p>[1]<cite>
P. Embrechts and M. V. Wüthrich.
&ldquo;Recent challenges in actuarial science&rdquo;.
In: <em>Annual Review of Statistics and Its Application</em> 9 (2022), pp. 119&ndash;140.
DOI: <a href="https://doi.org/10.1146/annurev-statistics-040120-030244">10.1146/annurev-statistics-040120-030244</a>.</cite></p>

<p>[2]<cite>
A. Mashrur, W. Luo, N. A. Zaidi, et al.
&ldquo;Machine learning for financial risk management: a survey&rdquo;.
In: <em>Ieee Access</em> 8 (2020), pp. 203203&ndash;203223.
DOI: <a href="https://doi.org/10.1109/ACCESS.2020.3036322">10.1109/ACCESS.2020.3036322</a>.</cite></p>

<p>[3]<cite>
M. V. Wüthrich and M. Merz.
<em>Statistical foundations of actuarial learning and its applications</em>.
Springer Nature, 2023.
DOI: <a href="https://doi.org/10.1007/978-3-031-12409-9.pdf">10.1007/978-3-031-12409-9.pdf</a>.</cite></p>

# Claim severity modeling


<p>[1]<cite>
H. Alsuhabi.
&ldquo;The new Topp-Leone exponentied exponential model for modeling financial data&rdquo;.
In: <em>Mathematical Modelling and Control</em> 4.1 (2024), p. 44.
DOI: <a href="https://doi.org/10.3934/mmc.2024005">10.3934/mmc.2024005</a>.</cite></p>

<p>[2]<cite>
S. A. Bakar and S. Nadarajah.
&ldquo;Composite models with underlying folded distributions&rdquo;.
In: <em>Journal of Computational and Applied Mathematics</em> 390 (2021), p. 113351.
DOI: <a href="https://doi.org/10.1016/j.cam.2020.113351">10.1016/j.cam.2020.113351</a>.</cite></p>

<p>[3]<cite>
A. Chaturvedi, S. R. Bapat, and N. Joshi.
&ldquo;Sequential estimation of an inverse Gaussian mean with known coefficient of variation&rdquo;.
In: <em>Sankhya B</em> 84.1 (2022), pp. 402&ndash;420.
DOI: <a href="https://doi.org/10.1007/s13571-021-00266-x">10.1007/s13571-021-00266-x</a>.</cite></p>

<p>[4]<cite>
D. Chevalier and M. Côté.
&ldquo;From point to probabilistic gradient boosting for claim frequency and severity prediction&rdquo;.
In: <em>European Actuarial Journal</em> 15.3 (2025), pp. 707&ndash;752.
DOI: <a href="https://doi.org/10.1007/s13385-025-00428-5">10.1007/s13385-025-00428-5</a>.</cite></p>

<p>[5]<cite>
S. Ghaddab, M. Kacem, C. de
Peretti, et al.
&ldquo;Extreme severity modeling using a GLM-GPD combination: application to an excess of loss reinsurance treaty&rdquo;.
In: <em>Empirical Economics</em> 65.3 (2023), pp. 1105&ndash;1127.
DOI: <a href="https://doi.org/10.1007/s00181-023-02371-4">10.1007/s00181-023-02371-4</a>.</cite></p>

<p>[6]<cite>
F. Holvoet, K. Antonio, and R. Henckaerts.
&ldquo;Neural networks for insurance pricing with frequency and severity data: a benchmark study from data preprocessing to technical tariff&rdquo;.
In: <em>North American Actuarial Journal</em> 29.3 (2025), pp. 519&ndash;562.
DOI: <a href="https://doi.org/10.1080/10920277.2025.2451860">10.1080/10920277.2025.2451860</a>.</cite></p>

<p>[7]<cite>
M. A. Meraou, N. M. Al-Kandari, M. Z. Raqab, et al.
&ldquo;Analysis of skewed data by using compound Poisson exponential distribution with applications to insurance claims&rdquo;.
In: <em>Journal of Statistical Computation and Simulation</em> 92.5 (2022), pp. 928&ndash;956.
DOI: <a href="https://doi.org/10.1080/00949655.2021.1981324">10.1080/00949655.2021.1981324</a>.</cite></p>

<p>[8]<cite>
L. Möstel, M. Fischer, and M. Pfeuffer.
&ldquo;Composite Tukey-type distributions with application to operational risk management&rdquo;.
In: <em>Journal of Operational Risk</em> (2024).
DOI: <a href="https://doi.org/10.21314/JOP.2023.010">10.21314/JOP.2023.010</a>.</cite></p>

<p>[9]<cite>
G. Pittarello, M. Hiabu, and A. M. Villegas.
&ldquo;Replicating and extending chain-ladder via an age&ndash;period&ndash;cohort structure on the claim development in a run-off triangle&rdquo;.
In: <em>North American Actuarial Journal</em> 30.1 (2026), pp. 1&ndash;31.
DOI: <a href="https://doi.org/10.1080/10920277.2025.2496725">10.1080/10920277.2025.2496725</a>.</cite></p>

<p>[10]<cite>
N. Počuča, P. Jevtić, P. D. McNicholas, et al.
&ldquo;Modeling frequency and severity of claims with the zero-inflated generalized cluster-weighted models&rdquo;.
In: <em>Insurance: Mathematics and Economics</em> 94 (2020), pp. 79&ndash;93.
DOI: <a href="https://doi.org/10.1016/j.insmatheco.2020.06.004">10.1016/j.insmatheco.2020.06.004</a>.</cite></p>

<p>[11]<cite>
A. Punzo.
&ldquo;A new look at the inverse Gaussian distribution with applications to insurance and economic data&rdquo;.
In: <em>Journal of Applied Statistics</em> 46.7 (2019), pp. 1260&ndash;1287.
DOI: <a href="https://doi.org/10.1080/02664763.2018.1542668">10.1080/02664763.2018.1542668</a>.
eprint: https://doi.org/10.1080/02664763.2018.1542668.
URL: <a href="https://doi.org/10.1080/02664763.2018.1542668">https://doi.org/10.1080/02664763.2018.1542668</a>.</cite></p>

<p>[12]<cite>
M. Qazvini.
&ldquo;On the validation of claims with excess zeros in liability insurance: A comparative study&rdquo;.
In: <em>Risks</em> 7.3 (2019), p. 71.
DOI: <a href="https://doi.org/10.3390/risks7030071">10.3390/risks7030071</a>.</cite></p>

<p>[13]<cite>
M. Raschke.
&ldquo;Alternative modelling and inference methods for claim size distributions&rdquo;.
In: <em>Annals of Actuarial Science</em> 14.1 (2020), pp. 1&ndash;19.
DOI: <a href="https://doi.org/10.1017/S1748499519000010">10.1017/S1748499519000010</a>.</cite></p>

<p>[14]<cite>
S. D. Tomarchio, A. Punzo, J. T. Ferreira, et al.
&ldquo;Mode mixture of unimodal distributions for insurance loss data&rdquo;.
In: <em>Annals of Operations Research</em> (2024), pp. 1&ndash;19.
DOI: <a href="https://doi.org/10.1007/s10479-024-06063-9">10.1007/s10479-024-06063-9</a>.</cite></p>

# Claim frequency modeling


<p>[1]<cite>
D. Chevalier and M. Côté.
&ldquo;From point to probabilistic gradient boosting for claim frequency and severity prediction&rdquo;.
In: <em>European Actuarial Journal</em> 15.3 (2025), pp. 707&ndash;752.
DOI: <a href="https://doi.org/10.1007/s13385-025-00428-5">10.1007/s13385-025-00428-5</a>.</cite></p>

<p>[2]<cite>
Ł. Delong, M. Lindholm, and M. V. Wüthrich.
&ldquo;Making Tweedie's compound Poisson model more accessible&rdquo;.
In: <em>European Actuarial Journal</em> 11.1 (2021), pp. 185&ndash;226.
DOI: <a href="https://doi.org/10.1007/s13385-021-00264-3">10.1007/s13385-021-00264-3</a>.</cite></p>

<p>[3]<cite>
F. Holvoet, K. Antonio, and R. Henckaerts.
&ldquo;Neural networks for insurance pricing with frequency and severity data: a benchmark study from data preprocessing to technical tariff&rdquo;.
In: <em>North American Actuarial Journal</em> 29.3 (2025), pp. 519&ndash;562.
DOI: <a href="https://doi.org/10.1080/10920277.2025.2451860">10.1080/10920277.2025.2451860</a>.</cite></p>

<p>[4]<cite>
Y. Liu, W. Li, and X. Zhang.
&ldquo;A marginalized zero-truncated Poisson regression model and its model averaging prediction: Y. Liu et al.&rdquo;
In: <em>Communications in Mathematics and Statistics</em> 13.3 (2025), pp. 527&ndash;570.
DOI: <a href="https://doi.org/10.1007/s40304-022-00312-8">10.1007/s40304-022-00312-8</a>.</cite></p>

<p>[5]<cite>
M. A. Meraou, N. M. Al-Kandari, M. Z. Raqab, et al.
&ldquo;Analysis of skewed data by using compound Poisson exponential distribution with applications to insurance claims&rdquo;.
In: <em>Journal of Statistical Computation and Simulation</em> 92.5 (2022), pp. 928&ndash;956.
DOI: <a href="https://doi.org/10.1080/00949655.2021.1981324">10.1080/00949655.2021.1981324</a>.</cite></p>

<p>[6]<cite>
M. A. Meraou, M. Z. Raqab, and F. B. Almathkour.
&ldquo;Analyzing insurance data with an alpha power transformed exponential Poisson model&rdquo;.
In: <em>Annals of Data Science</em> 12.3 (2025), pp. 991&ndash;1011.
DOI: <a href="https://doi.org/10.1007/s40745-024-00554-z">10.1007/s40745-024-00554-z</a>.</cite></p>

<p>[7]<cite>
J. Merupula, V. Vaidyanathan, and C. Chesneau.
&ldquo;Prediction Interval for Compound Conway&ndash;Maxwell&ndash;Poisson Regression Model with Application to Vehicle Insurance Claim Data&rdquo;.
In: <em>Mathematical and Computational Applications</em> 28.2 (2023), p. 39.
DOI: <a href="https://doi.org/10.3390/mca28020039">10.3390/mca28020039</a>.</cite></p>

<p>[8]<cite>
N. Počuča, P. Jevtić, P. D. McNicholas, et al.
&ldquo;Modeling frequency and severity of claims with the zero-inflated generalized cluster-weighted models&rdquo;.
In: <em>Insurance: Mathematics and Economics</em> 94 (2020), pp. 79&ndash;93.
DOI: <a href="https://doi.org/10.1016/j.insmatheco.2020.06.004">10.1016/j.insmatheco.2020.06.004</a>.</cite></p>

<p>[9]<cite>
G. Willame, J. Trufin, and M. Denuit.
&ldquo;Boosted Poisson regression trees: a guide to the BT package in R&rdquo;.
In: <em>Annals of Actuarial Science</em> 18.3 (2024), pp. 605&ndash;625.
DOI: <a href="https://doi.org/10.1017/S174849952300026X">10.1017/S174849952300026X</a>.</cite></p>

# Risk measure


<p>[1]<cite>
A. G. Abubakari.
&ldquo;Actuarial measures, regression, and applications of exponentiated Fréchet loss distribution&rdquo;.
In: <em>International Journal of Mathematics and Mathematical Sciences</em> 2022.1 (2022), p. 3155188.
DOI: <a href="https://doi.org/10.1155/2022/3155188">10.1155/2022/3155188</a>.</cite></p>

<p>[2]<cite>
A. Y. Bin-Nun, C. Lizarazo, A. Panasci, et al.
&ldquo;What do surrogate safety metrics measure? Understanding driving safety as a continuum&rdquo;.
In: <em>Accident Analysis &amp; Prevention</em> 195 (2024), p. 107245.
DOI: <a href="https://doi.org/10.1016/j.aap.2023.107245">10.1016/j.aap.2023.107245</a>.</cite></p>

<p>[3]<cite>
Y. Guan, Z. Jiao, and R. Wang.
&ldquo;A reverse ES (CVaR) optimization formula&rdquo;.
In: <em>North American Actuarial Journal</em> 28.3 (2024), pp. 611&ndash;625.
DOI: <a href="https://doi.org/10.1080/10920277.2023.2249524">10.1080/10920277.2023.2249524</a>.</cite></p>

<p>[4]<cite>
A. Staino, E. Russo, M. Costabile, et al.
&ldquo;Minimum capital requirement and portfolio allocation for non-life insurance: a semiparametric model with Conditional Value-at-Risk (CVaR) constraint: A. Staino et al.&rdquo;
In: <em>Computational Management Science</em> 20.1 (2023), p. 12.
DOI: <a href="https://doi.org/10.1007/s10287-023-00439-1">10.1007/s10287-023-00439-1</a>.</cite></p>

# Pricing insurance


<p>[1]<cite>
A. Brauer.
&ldquo;Enhancing actuarial non-life pricing models via transformers&rdquo;.
In: <em>European Actuarial Journal</em> 14.3 (2024), pp. 991&ndash;1012.
DOI: <a href="https://doi.org/10.1007/s13385-024-00388-2">10.1007/s13385-024-00388-2</a>.</cite></p>

<p>[2]<cite>
Ł. Delong, M. Lindholm, and M. V. Wüthrich.
&ldquo;Making Tweedie's compound Poisson model more accessible&rdquo;.
In: <em>European Actuarial Journal</em> 11.1 (2021), pp. 185&ndash;226.
DOI: <a href="https://doi.org/10.1007/s13385-021-00264-3">10.1007/s13385-021-00264-3</a>.</cite></p>

<p>[3]<cite>
F. Holvoet, K. Antonio, and R. Henckaerts.
&ldquo;Neural networks for insurance pricing with frequency and severity data: a benchmark study from data preprocessing to technical tariff&rdquo;.
In: <em>North American Actuarial Journal</em> 29.3 (2025), pp. 519&ndash;562.
DOI: <a href="https://doi.org/10.1080/10920277.2025.2451860">10.1080/10920277.2025.2451860</a>.</cite></p>

<p>[4]<cite>
M. Lindholm, F. Lindskog, and J. Palmquist.
&ldquo;Local bias adjustment, duration-weighted probabilities, and automatic construction of tariff cells&rdquo;.
In: <em>Scandinavian Actuarial Journal</em> 2023.10 (2023), pp. 946&ndash;973.
DOI: <a href="https://doi.org/10.1080/03461238.2023.2176251">10.1080/03461238.2023.2176251</a>.</cite></p>

<p>[5]<cite>
M. Lindholm and T. Nazar.
&ldquo;On duration effects in non-life insurance pricing&rdquo;.
In: <em>European Actuarial Journal</em> 14.3 (2024), pp. 809&ndash;832.
DOI: <a href="https://doi.org/10.1007/s13385-024-00385-5">10.1007/s13385-024-00385-5</a>.</cite></p>

<p>[6]<cite>
M. Lindholm and J. Palmquist.
&ldquo;Black-box guided generalised linear model building with non-life pricing applications&rdquo;.
In: <em>Annals of Actuarial Science</em> 18.3 (2024), pp. 675&ndash;691.
DOI: <a href="https://doi.org/10.1017/S1748499524000265">10.1017/S1748499524000265</a>.</cite></p>

<p>[7]<cite>
M. A. Meraou, N. M. Al-Kandari, M. Z. Raqab, et al.
&ldquo;Analysis of skewed data by using compound Poisson exponential distribution with applications to insurance claims&rdquo;.
In: <em>Journal of Statistical Computation and Simulation</em> 92.5 (2022), pp. 928&ndash;956.
DOI: <a href="https://doi.org/10.1080/00949655.2021.1981324">10.1080/00949655.2021.1981324</a>.</cite></p>

<p>[8]<cite>
M. Meraou, N. Al-Kandari, and M. Raqab.
&ldquo;Univariate and bivariate compound models based on random sum of variates with application to the insurance losses data&rdquo;.
In: <em>Journal of Statistical Theory and Practice</em> 16.4 (2022), p. 56.
DOI: <a href="https://doi.org/10.1007/s42519-022-00282-8">10.1007/s42519-022-00282-8</a>.</cite></p>

<p>[9]<cite>
R. Wang, H. Shi, and J. Cao.
&ldquo;A Nested GLM Framework with Neural Network Encoding and Spatially Constrained Clustering in Non-Life Insurance Ratemaking&rdquo;.
In: <em>North American Actuarial Journal</em> 29.3 (2025), pp. 645&ndash;661.
DOI: <a href="https://doi.org/10.1080/10920277.2024.2442416">10.1080/10920277.2024.2442416</a>.</cite></p>

<p>[10]<cite>
X. Xin and F. Huang.
&ldquo;Antidiscrimination insurance pricing: Regulations, fairness criteria, and models&rdquo;.
In: <em>North American Actuarial Journal</em> 28.2 (2024), pp. 285&ndash;319.
DOI: <a href="https://doi.org/10.1080/10920277.2023.2190528">10.1080/10920277.2023.2190528</a>.</cite></p>

# Extreme value analysis


<p>[1]<cite>
M. Allouche, J. El Methni, and S. Girard.
&ldquo;A refined Weissman estimator for extreme quantiles&rdquo;.
In: <em>Extremes</em> 26.3 (2023), pp. 545&ndash;572.
DOI: <a href="https://doi.org/10.1007/s10687-022-00452-8">10.1007/s10687-022-00452-8</a>.</cite></p>

<p>[2]<cite>
S. Girard, G. Stupfler, and A. Usseglio-Carleve.
&ldquo;On automatic bias reduction for extreme expectile estimation&rdquo;.
In: <em>Statistics and Computing</em> 32.4 (2022), p. 64.
DOI: <a href="https://doi.org/10.1007/s11222-022-10118-x">10.1007/s11222-022-10118-x</a>.</cite></p>

<p>[3]<cite>
J. Meng and K. Chan.
&ldquo;Penalized quasi-likelihood estimation of generalized Pareto regression&ndash;consistent identification of risk factors for extreme losses&rdquo;.
In: <em>Insurance: Mathematics and Economics</em> 104 (2022), pp. 60&ndash;75.
DOI: <a href="https://doi.org/10.1016/j.insmatheco.2022.01.005">10.1016/j.insmatheco.2022.01.005</a>.</cite></p>

<p>[4]<cite>
G. Stupfler and A. Usseglio-Carleve.
&ldquo;Composite bias-reduced L p-quantile-based estimators of extreme quantiles and expectiles&rdquo;.
In: <em>Canadian Journal of Statistics</em> 51.2 (2023), pp. 704&ndash;742.
DOI: <a href="https://doi.org/10.1002/cjs.11703">10.1002/cjs.11703</a>.</cite></p>

# Multivariate and copula models


<p>[1]<cite>
A. Brouste, C. Dutang, L. Hovsepyan, et al.
&ldquo;Fast inference in copula models with categorical explanatory variables using the one-step procedure&rdquo;.
In: <em>Computational Statistics</em> 41.1 (2026), p. 23.
DOI: <a href="https://doi.org/10.1007/s00180-025-01692-5">10.1007/s00180-025-01692-5</a>.</cite></p>

<p>[2]<cite>
N. W. Deresa, I. Van Keilegom, and K. Antonio.
&ldquo;Copula-based inference for bivariate survival data with left truncation and dependent censoring&rdquo;.
In: <em>Insurance: Mathematics and Economics</em> 107 (2022), pp. 1&ndash;21.
DOI: <a href="https://doi.org/10.1016/j.insmatheco.2022.07.011">10.1016/j.insmatheco.2022.07.011</a>.</cite></p>

<p>[3]<cite>
Q. Hoang, P. Khandelwal, and S. Ghosh.
&ldquo;Robust predictive model using copulas&rdquo;.
In: <em>Data-Enabled Discovery and Applications</em> 3.1 (2019), p. 8.
DOI: <a href="https://doi.org/10.1007/s41688-019-0032-y">10.1007/s41688-019-0032-y</a>.</cite></p>

<p>[4]<cite>
M. Meraou, N. Al-Kandari, and M. Raqab.
&ldquo;Univariate and bivariate compound models based on random sum of variates with application to the insurance losses data&rdquo;.
In: <em>Journal of Statistical Theory and Practice</em> 16.4 (2022), p. 56.
DOI: <a href="https://doi.org/10.1007/s42519-022-00282-8">10.1007/s42519-022-00282-8</a>.</cite></p>

<p>[5]<cite>
S. F. Syed Yusoff Alhabshi, Z. H. Zamzuri, and S. N. Mohd Ramli.
&ldquo;Monte carlo simulation of the moments of a copula-dependent risk process with weibull interwaiting time&rdquo;.
In: <em>Risks</em> 9.6 (2021), p. 109.
DOI: <a href="https://doi.org/10.3390/risks9060109">10.3390/risks9060109</a>.</cite></p>

# Bayesian analysis


<p>[1]<cite>
P. Goffard and P. J. Laub.
&ldquo;Approximate Bayesian Computations to fit and compare insurance loss models&rdquo;.
In: <em>Insurance: Mathematics and Economics</em> 100 (2021), pp. 350&ndash;371.
DOI: <a href="https://doi.org/10.1016/j.insmatheco.2021.06.002">10.1016/j.insmatheco.2021.06.002</a>.</cite></p>

<p>[2]<cite>
F. Ungolo and E. R. van den
Heuvel.
&ldquo;A Dirichlet process mixture regression model for the analysis of competing risk events&rdquo;.
In: <em>Insurance: Mathematics and Economics</em> 116 (2024), pp. 95&ndash;113.
DOI: <a href="https://doi.org/10.1016/j.insmatheco.2024.02.004">10.1016/j.insmatheco.2024.02.004</a>.</cite></p>

# Other topics


<p>[1]<cite>
H. M. Aljohani.
&ldquo;Statistical inference for a novel distribution using ranked set sampling with applications&rdquo;.
In: <em>Heliyon</em> 10.5 (2024).
DOI: <a href="https://doi.org/10.1016/j.heliyon.2024.e26893">10.1016/j.heliyon.2024.e26893</a>.</cite></p>

<p>[2]<cite>
B. Avanzi, E. Dong, P. J. Laub, et al.
&ldquo;Distributional refinement network: Distributional forecasting via deep learning&rdquo;.
In: <em>Insurance: Mathematics and Economics</em> (2026), p. 103246.
DOI: <a href="https://doi.org/10.1016/j.insmatheco.2026.103246">10.1016/j.insmatheco.2026.103246</a>.</cite></p>

<p>[3]<cite>
B. Avanzi, G. Taylor, and M. Wang.
&ldquo;SPLICE: a synthetic paid loss and incurred cost experience simulator&rdquo;.
In: <em>Annals of Actuarial Science</em> 17.1 (2023), pp. 7&ndash;35.
DOI: <a href="https://doi.org/10.1017/S1748499522000057">10.1017/S1748499522000057</a>.</cite></p>

<p>[4]<cite>
M. Bladt and C. B. Gardner.
&ldquo;Joint discrete and continuous matrix distribution modeling&rdquo;.
In: <em>Stochastic Models</em> 40.1 (2024), pp. 1&ndash;37.
DOI: <a href="https://doi.org/10.1080/15326349.2023.2185257">10.1080/15326349.2023.2185257</a>.</cite></p>

<p>[5]<cite>
A. Brouste, C. Dutang, and T. Rohmer.
&ldquo;A closed-form alternative estimator for GLM with categorical explanatory variables&rdquo;.
In: <em>Communications in Statistics-Simulation and Computation</em> 53.5 (2024), pp. 2444&ndash;2460.
DOI: <a href="https://doi.org/10.1080/03610918.2022.2076870">10.1080/03610918.2022.2076870</a>.</cite></p>

<p>[6]<cite>
R. Henckaerts, K. Antonio, and M. Côté.
&ldquo;When stakes are high: Balancing accuracy and transparency with Model-Agnostic Interpretable Data-driven suRRogates&rdquo;.
In: <em>Expert Systems with Applications</em> 202 (2022), p. 117230.
DOI: <a href="https://doi.org/10.1016/j.eswa.2022.117230">10.1016/j.eswa.2022.117230</a>.</cite></p>

<p>[7]<cite>
D. Lim, A. Neufeld, S. Sabanis, et al.
&ldquo;Langevin dynamics based algorithm e-TH $\varepsilon$ O POULA for stochastic optimization problems with discontinuous stochastic gradient&rdquo;.
In: <em>Mathematics of Operations Research</em> 50.3 (2025), pp. 2333&ndash;2374.
DOI: <a href="https://doi.org/10.1287/moor.2022.0307">10.1287/moor.2022.0307</a>.</cite></p>

<p>[8]<cite>
A. Majeed.
&ldquo;Accelerated failure time models: An application in insurance attrition&rdquo;.
In: <em>The Journal of Risk Management and Insurance</em> (2020).</cite></p>

<p>[9]<cite>
T. Miljkovic and D. Fernández.
&ldquo;On two mixture-based clustering approaches used in modeling an insurance portfolio&rdquo;.
In: <em>Risks</em> 6.2 (2018), p. 57.
DOI: <a href="https://doi.org/10.3390/risks6020057">10.3390/risks6020057</a>.</cite></p>

<p>[10]<cite>
T. Miljkovic and P. Wang.
&ldquo;A dimension reduction assisted credit scoring method for big data with categorical features&rdquo;.
In: <em>Financial Innovation</em> 11.1 (2025), p. 29.
DOI: <a href="https://doi.org/10.1186/s40854-024-00689-1">10.1186/s40854-024-00689-1</a>.</cite></p>

<p>[11]<cite>
J. Ponnet, J. Raymaekers, and T. Verdonck.
&ldquo;Fast thresholded concordance probability for evolutionary optimization&rdquo;.
In: <em>Swarm and Evolutionary Computation</em> 78 (2023), p. 101260.
DOI: <a href="https://doi.org/10.1016/j.swevo.2023.101260">10.1016/j.swevo.2023.101260</a>.</cite></p>

<p>[12]<cite>
R. Richman and M. V. Wüthrich.
&ldquo;LocalGLMnet: interpretable deep learning for tabular data&rdquo;.
In: <em>Scandinavian Actuarial Journal</em> 2023.1 (2023), pp. 71&ndash;95.
DOI: <a href="https://doi.org/10.1080/03461238.2022.2081816">10.1080/03461238.2022.2081816</a>.</cite></p>

<p>[13]<cite>
R. Richman and M. V. Wüthrich.
&ldquo;Nagging predictors&rdquo;.
In: <em>Risks</em> 8.3 (2020), p. 83.
DOI: <a href="https://doi.org/10.3390/risks8030083">10.3390/risks8030083</a>.</cite></p>

<p>[14]<cite>
P. Shi and K. Shi.
&ldquo;Non-life insurance risk classification using categorical embedding&rdquo;.
In: <em>North American Actuarial Journal</em> 27.3 (2023), pp. 579&ndash;601.
DOI: <a href="https://doi.org/10.1080/10920277.2022.2123361">10.1080/10920277.2022.2123361</a>.</cite></p>

<p>[15]<cite>
S. C. Tseung, A. L. Badescu, T. C. Fung, et al.
&ldquo;LRMoE.jl: a software package for insurance loss modelling using mixture of experts regression model&rdquo;.
In: <em>Annals of Actuarial Science</em> 15.2 (2021), pp. 419&ndash;440.
DOI: <a href="https://doi.org/10.1017/S1748499521000087">10.1017/S1748499521000087</a>.</cite></p>

<p>[16]<cite>
M. V. Wüthrich and J. Ziegel.
&ldquo;Isotonic recalibration under a low signal-to-noise ratio&rdquo;.
In: <em>Scandinavian Actuarial Journal</em> 2024.3 (2024), pp. 279&ndash;299.
DOI: <a href="https://doi.org/10.1080/03461238.2023.2246743">10.1080/03461238.2023.2246743</a>.</cite></p>



