<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Mortality Table Analysis in Actuarial Science: A Study on French Mortality Data • CASdatasets</title>
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.4.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="mortality_vignette_files/libs/quarto-html/popper.min.js"></script><script src="mortality_vignette_files/libs/quarto-html/tippy.umd.min.js"></script><link href="mortality_vignette_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="mortality_vignette_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link rel="stylesheet" href="style.scss">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Mortality Table Analysis in Actuarial Science: A Study on French Mortality Data">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">CASdatasets</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">1.2-0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../articles/CASdatasets.html">Get started</a></li>
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles">
<li><a class="dropdown-item" href="../articles/poisson_vignette.html">Frequency analysis of a French Motor Third Party Liability dataset</a></li>
    <li><a class="dropdown-item" href="../articles/quasi_poisson_vignette_ausprivauto0405.html">Frequency analysis of an Australian Motor Third Party Liability dataset</a></li>
    <li><a class="dropdown-item" href="../articles/gam_rc_phileas_vignette.html">Frequency analysis of a Belgian Motor Third Party Liability dataset</a></li>
    <li><a class="dropdown-item" href="../articles/zero_inflated_vignette.html">Frequency analysis of a Norwegian Motor Third Party Liability dataset</a></li>
    <li><a class="dropdown-item" href="../articles/zero_inflated_vignette_freMTPL.html">Frequency analysis with a Zero Inflated Regression of a French Motor Third Party Liability dataset</a></li>
    <li><a class="dropdown-item" href="../articles/triangle_vignette.html">Claims reserving of a French Motor Third Party Liability triangle dataset</a></li>
    <li><a class="dropdown-item" href="../articles/triangle_aids_vignette.html">Reserving exercice on reporting delays in AIDS Data</a></li>
    <li><a class="dropdown-item" href="../articles/mortality_vignette.html">Mortality Table Analysis in Actuarial Science: A Study on French Mortality Data</a></li>
    <li><a class="dropdown-item" href="../articles/calibration_metrics_vignette.html">Calibration Metrics for Random Forest and Generalized Linear Model Using French Insurance Data</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/dutangc/CASdatasets/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">

      <h1>Mortality Table Analysis in Actuarial Science: A Study on French Mortality Data</h1>

      <p class="author">Julien Siharath</p>
      <p class="date">October, 2024</p>

      <small class="dont-index">Source: <a href="https://github.com/dutangc/CASdatasets/blob/master/vignettes/mortality_vignette.qmd" class="external-link"><code>vignettes/mortality_vignette.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <section class="section level2"><h2 id="sec-poisson-introduction">Introduction<a class="anchor" aria-label="anchor" href="#sec-poisson-introduction"></a>
</h2>
<div class="cell">
<details class="code-fold"><summary>Session Settings</summary><div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Graphs----</span></span>
<span><span class="va">face_text</span><span class="op">=</span><span class="st">'plain'</span></span>
<span><span class="va">face_title</span><span class="op">=</span><span class="st">'plain'</span></span>
<span><span class="va">size_title</span> <span class="op">=</span> <span class="fl">14</span></span>
<span><span class="va">size_text</span> <span class="op">=</span> <span class="fl">11</span></span>
<span><span class="va">legend_size</span> <span class="op">=</span> <span class="fl">11</span></span>
<span></span>
<span><span class="va">global_theme</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu">theme_minimal</span><span class="op">(</span><span class="op">)</span> <span class="op">%+replace%</span></span>
<span>    <span class="fu">theme</span><span class="op">(</span></span>
<span>      text <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size <span class="op">=</span> <span class="va">size_text</span>, face <span class="op">=</span> <span class="va">face_text</span><span class="op">)</span>,</span>
<span>      legend.position <span class="op">=</span> <span class="st">"bottom"</span>,</span>
<span>      legend.direction <span class="op">=</span> <span class="st">"horizontal"</span>, </span>
<span>      legend.box <span class="op">=</span> <span class="st">"vertical"</span>,</span>
<span>      legend.key <span class="op">=</span> <span class="fu">element_blank</span><span class="op">(</span><span class="op">)</span>,</span>
<span>      legend.text <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size <span class="op">=</span> <span class="va">legend_size</span><span class="op">)</span>,</span>
<span>      axis.text <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>size <span class="op">=</span> <span class="va">size_text</span>, face <span class="op">=</span> <span class="va">face_text</span><span class="op">)</span>, </span>
<span>      plot.title <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span></span>
<span>        size <span class="op">=</span> <span class="va">size_title</span>, </span>
<span>        hjust <span class="op">=</span> <span class="fl">0.5</span></span>
<span>      <span class="op">)</span>,</span>
<span>      plot.subtitle <span class="op">=</span> <span class="fu">element_text</span><span class="op">(</span>hjust <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Outputs</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span><span class="st">"digits"</span> <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
</details>
</div>
<div class="cell">
<style type="text/css">
.justify {
  text-align: justify !important
}
</style>
</div>
<div>
<blockquote>
<p><strong>In Brief</strong></p>
<p>This study focuses on the analysis and application of mortality tables within actuarial science, with a particular emphasis on examining French mortality data. Although the Lee-Carter model is widely used for mortality projections, it has significant limitations, particularly in its sensitivity to outliers. Outliers can skew mortality rate estimations, leading to inaccurate forecasts—an issue of critical importance in actuarial work.</p>
<p>To address this challenge, we utilize the <code>rainbow</code> package for detecting outliers in the dataset, followed by the application of the <code>HUrob</code> method. The <code>HUrob</code> method is a robust statistical approach specifically designed to mitigate the influence of outliers, thereby ensuring more accurate and reliable mortality forecasts.</p>
<p>This document provides a comprehensive guide, covering each stage from data importation to advanced modeling and the interpretation of results, equipping readers with the necessary tools to perform robust mortality analysis in actuarial contexts.</p>
</blockquote>
</div>
<section class="level2"><h3 id="required-packages">Required Packages<a class="anchor" aria-label="anchor" href="#required-packages"></a>
</h3>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">required_libraries</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"CASdatasets"</span>,</span>
<span>  <span class="st">"tidyverse"</span>, </span>
<span>  <span class="st">"demography"</span>,</span>
<span>  <span class="st">"rainbow"</span>,</span>
<span>  <span class="st">"forecast"</span>,</span>
<span>  <span class="st">"kableExtra"</span>,</span>
<span>  <span class="st">"RColorBrewer"</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/invisible.html" class="external-link">invisible</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html" class="external-link">lapply</a></span><span class="op">(</span><span class="va">required_libraries</span>, <span class="va">library</span>, character.only <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</details>
</div>
</section><section class="level2"><h3 id="data">Data<a class="anchor" aria-label="anchor" href="#data"></a>
</h3>
<div class="justify">
<p>The data used in this vignette are sourced from the Human Mortality Database (HMD), a collaborative project by the Max Planck Institute for Demographic Research (Germany), University of California, Berkeley (USA), and French Institute for Demographic Studies (France). Available <a href="www.mortality.org">here</a>.</p>
<p>It is a comprehensive repository of detailed mortality and population data. The dataset contains age-specific mortality rates for France, which are critical for analyzing mortality trends and making future projections. Accurate mortality data serves as the foundation for many actuarial tasks, including premium setting, reserve calculation, and the assessment of pension fund solvency.</p>
<p>The dataset is accessed via the <code>hmd.mx</code> function from the <code>demography</code> package, which facilitates the direct download of mortality data from the HMD. The data is structured as a <code>demogdata</code> object, comprising the following components:</p>
<ul>
<li>
<strong>Years</strong>: A vector indicating the range of years for which mortality data is available (e.g., 1900-2022).</li>
<li>
<strong>Ages</strong>: A vector representing the specific ages for which mortality rates are recorded, typically ranging from 0 to 110+.</li>
<li>
<strong>Rates</strong>: A matrix where each row corresponds to a specific age and each column represents a year. The values are the logarithms of mortality rates, defined as the natural logarithm of the number of deaths per 1,000 individuals at a specific age and year.</li>
<li>
<strong>Population</strong>: A matrix analogous to the rates matrix, representing the population exposed to risk at each age and year.</li>
<li>
<strong>Deaths</strong>: A matrix that captures the actual number of deaths recorded for each age and year.</li>
<li>
<strong>Type</strong>: A character string that specifies whether the data pertains to “male”, “female”, or “total” populations.</li>
</ul>
</div>
</section><section class="level2"><h3 id="purpose">Purpose<a class="anchor" aria-label="anchor" href="#purpose"></a>
</h3>
<div class="justify">
<p>In the aftermath of a wars or significant public health event, mortality rates can fluctuate unpredictably. For insurance companies, this variability presents a critical challenge: accurately forecasting mortality rates is essential for pricing life insurance policies, determining annuity payments, and calculating the reserves required to cover future claims. If mortality forecasts are inaccurate, it could lead to substantial financial losses, threaten the solvency of an insurer, or impair its ability to meet obligations to policyholders. Therefore, precise and reliable mortality forecasting is not just an academic exercise but a practical necessity for ensuring the financial stability and competitiveness of insurance products.</p>
<p>To address these challenges, this vignette provides a practical and comprehensive guide to analyzing mortality tables, with a specific focus on French mortality data. We will demonstrate the application of advanced actuarial methods to improve mortality forecasting, ensuring that the forecasts remain robust even in the presence of anomalies such as outliers.</p>
<p>To achieve this, we will first utilize the <strong>Lee-Carter model</strong>, a widely recognized method for mortality projections. This model is effective in capturing long-term mortality trends but is sensitive to outliers—an issue that can lead to distorted mortality rate estimates and inaccurate forecasts.</p>
<p>To mitigate these risks, we will demonstrate the use of the <strong>rainbow package</strong> for detecting outliers in the dataset. Identifying and managing outliers is crucial for maintaining the accuracy of forecasts. Following this, we will implement the <strong>HUrob method</strong>, a robust statistical approach specifically designed to reduce the impact of outliers. By employing <code>HUrob</code>, we can ensure that our mortality forecasts are both accurate and reliable, even in the presence of data anomalies.</p>
<p>In summary, this vignette will guide you through a practical approach to improving mortality forecasts, directly addressing the challenges insurers face in an unpredictable world. By following these methods, you will be better equipped to manage the financial risks associated with fluctuating mortality rates, ensuring the solvency and stability of insurance operations.</p>
</div>
</section><section class="level2"><h3 id="importation">Importation<a class="anchor" aria-label="anchor" href="#importation"></a>
</h3>
<p>To access the Human Mortality Database (HMD) in R, you need to use the <code>demography</code> package. With your HMD login credentials, you can retrieve mortality data for specific countries using the <code>hmd.mx()</code> function. For example, to download data for France, you can use the country code <code>"FRATNP"</code>. Simply replace your email and password with your own credentials in the following code, and the data will be ready for analysis:</p>
<p><code>france &lt;- hmd.mx("FRATNP", "your email", "your password", label = "FRA")</code></p>
<p>In this vignette, we use a subset of the French HMD database hosted in CASdatasets name <code>freHMD</code>.</p>
</section></section><section class="section level2"><h2 id="overview-of-a-mortality-table">Overview of a Mortality Table<a class="anchor" aria-label="anchor" href="#overview-of-a-mortality-table"></a>
</h2>
<p>To stabilize the variance associated with high age-specific mortality rates, the raw data is automatically transformed by taking the logarithm in the plot function and other related functions within the <code>demography</code> package. This logarithmic transformation is particularly beneficial for actuaries, as it ensures that the model’s outputs are both reliable and interpretable across different age groups. This is crucial when assessing the risk profiles of various insurance products, where accurate and consistent modeling of mortality rates is essential. As a result, the mortality models discussed in this chapter are all presented on a log scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">france.sm</span> <span class="op">&lt;-</span> <span class="fu">smooth.demogdata</span><span class="op">(</span><span class="va">france</span>, obs.var <span class="op">=</span> <span class="st">"theoretical"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">colors</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/colorRamp.html" class="external-link">colorRampPalette</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/grDevices/palettes.html" class="external-link">rainbow</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="va">france.sm</span><span class="op">$</span><span class="va">year</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="va">france.sm</span><span class="op">$</span><span class="va">year</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">france.sm</span>, series <span class="op">=</span> <span class="st">"male"</span>, type <span class="op">=</span> <span class="st">"l"</span>,</span>
<span>     col <span class="op">=</span> <span class="va">colors</span>,</span>
<span>     main <span class="op">=</span> <span class="st">""</span>,</span>
<span>     ylab <span class="op">=</span> <span class="st">"Log-Mortality Rate"</span>, xlab <span class="op">=</span> <span class="st">"Age"</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">selected_years</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1900</span>, <span class="fl">1916</span>, <span class="fl">1943</span>, <span class="fl">2000</span>, <span class="fl">2020</span><span class="op">)</span></span>
<span><span class="va">legend_colors</span> <span class="op">&lt;-</span> <span class="va">colors</span><span class="op">[</span><span class="va">france.sm</span><span class="op">$</span><span class="va">year</span> <span class="op"><a href="https://rdrr.io/r/base/match.html" class="external-link">%in%</a></span> <span class="va">selected_years</span><span class="op">]</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html" class="external-link">legend</a></span><span class="op">(</span><span class="st">"bottomright"</span>, legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html" class="external-link">as.character</a></span><span class="op">(</span><span class="va">selected_years</span><span class="op">)</span>,</span>
<span>       col <span class="op">=</span> <span class="va">legend_colors</span>,</span>
<span>       lty <span class="op">=</span> <span class="fl">1</span>, </span>
<span>       title <span class="op">=</span> <span class="st">"Year"</span>, cex <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div id="fig-smoothed-male-mortality" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-smoothed-male-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 1: Smoothed Male Log-Mortality Rates from 1900 to 2022 in France
</figcaption><div aria-describedby="fig-smoothed-male-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mortality_vignette_files/figure-html/fig-smoothed-male-mortality-1.png" width="768">
</div>
</figure>
</div>
</div>
</div>
<div class="justify">
<p>The plot displays smoothed mortality rates over time, revealing a characteristic “U-shape” mortality pattern: high rates during infancy, a decline in early adulthood, and a steady increase with age. The smoothing technique effectively clarifies underlying trends by reducing noise in the data, making significant patterns more discernible. Notably, the plot highlights the impact of historical events, with distinct “humps” corresponding to increased mortality during World War I and World War II. Additionally, a noticeable decrease in mortality rates among younger populations over time is evident, reflecting improvements in public health and living conditions.</p>
<p>This visualization serves as a foundational tool for further analysis, including forecasting, outlier detection, and robust modeling, providing a clear starting point for more advanced actuarial assessments.</p>
</div>
</section><section class="section level2"><h2 id="fitting-the-lee-carter-model">Fitting the Lee-Carter Model<a class="anchor" aria-label="anchor" href="#fitting-the-lee-carter-model"></a>
</h2>
<section class="level2"><h3 id="lee-carter-model-structure">Lee-Carter Model Structure<a class="anchor" aria-label="anchor" href="#lee-carter-model-structure"></a>
</h3>
<p>The model structure proposed by <span class="citation" data-cites="lee1992">Lee and Carter (<a href="#ref-lee1992" role="doc-biblioref">1992</a>)</span> is represented by the following equation:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo>log</mo><mrow><mo stretchy="true" form="prefix">(</mo><msub><mi>m</mi><mrow><mi>x</mi><mo>,</mo><mi>t</mi></mrow></msub><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><msub><mi>a</mi><mi>x</mi></msub><mo>+</mo><msub><mi>b</mi><mi>x</mi></msub><msub><mi>k</mi><mi>t</mi></msub><mo>+</mo><msub><mi>ϵ</mi><mrow><mi>x</mi><mo>,</mo><mi>t</mi></mrow></msub><mo>,</mo><mspace width="1.0em"></mspace><mtext mathvariant="normal">(1)</mtext></mrow><annotation encoding="application/x-tex">
\log(m_{x,t}) = a_x + b_x k_t + \epsilon_{x,t}, \quad \text{(1)}
</annotation></semantics></math></p>
<p>Where:</p>
<ul>
<li>
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>a</mi><mi>x</mi></msub><annotation encoding="application/x-tex">a_x</annotation></semantics></math> represents the age-specific pattern of the log mortality rates averaged across years.</li>
<li>
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>b</mi><mi>x</mi></msub><annotation encoding="application/x-tex">b_x</annotation></semantics></math> is the first principal component, capturing the relative change in the log mortality rate at each age.</li>
<li>
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mi>t</mi></msub><annotation encoding="application/x-tex">k_t</annotation></semantics></math> denotes the first set of principal component scores for year <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>t</mi><annotation encoding="application/x-tex">t</annotation></semantics></math>, measuring the overall level of the log mortality rates.</li>
<li>
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>ϵ</mi><mrow><mi>x</mi><mo>,</mo><mi>t</mi></mrow></msub><annotation encoding="application/x-tex">\epsilon_{x,t}</annotation></semantics></math> is the residual at age <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>x</mi><annotation encoding="application/x-tex">x</annotation></semantics></math> and year <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>t</mi><annotation encoding="application/x-tex">t</annotation></semantics></math>, accounting for the model’s error term.</li>
</ul>
<p>The model assumes homoskedastic errors and is typically estimated using singular value decomposition (SVD), a method that efficiently extracts the principal components.</p>
<section class="level3"><h4 id="over-parameterization-and-identifiability">Over-Parameterization and Identifiability<a class="anchor" aria-label="anchor" href="#over-parameterization-and-identifiability"></a>
</h4>
<p>The Lee-Carter (LC) model in Equation (1) is over-parameterized, meaning that the model’s structure remains invariant under certain transformations:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="false" form="prefix">{</mo><msub><mi>a</mi><mi>x</mi></msub><mo>,</mo><msub><mi>b</mi><mi>x</mi></msub><mo>,</mo><msub><mi>k</mi><mi>t</mi></msub><mo stretchy="false" form="postfix">}</mo><mo>→</mo><mo stretchy="false" form="prefix">{</mo><msub><mi>a</mi><mi>x</mi></msub><mo>,</mo><msub><mi>b</mi><mi>x</mi></msub><mi>/</mi><mi>c</mi><mo>,</mo><mi>c</mi><msub><mi>k</mi><mi>t</mi></msub><mo stretchy="false" form="postfix">}</mo><mo>,</mo></mrow><annotation encoding="application/x-tex">
\{a_x, b_x, k_t\} \rightarrow \{a_x, b_x/c, c k_t\},
</annotation></semantics></math></p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="false" form="prefix">{</mo><msub><mi>a</mi><mi>x</mi></msub><mo>,</mo><msub><mi>b</mi><mi>x</mi></msub><mo>,</mo><msub><mi>k</mi><mi>t</mi></msub><mo stretchy="false" form="postfix">}</mo><mo>→</mo><mo stretchy="false" form="prefix">{</mo><msub><mi>a</mi><mi>x</mi></msub><mo>−</mo><mi>c</mi><msub><mi>b</mi><mi>x</mi></msub><mo>,</mo><msub><mi>b</mi><mi>x</mi></msub><mo>,</mo><msub><mi>k</mi><mi>t</mi></msub><mo>+</mo><mi>c</mi><mo stretchy="false" form="postfix">}</mo><mi>.</mi></mrow><annotation encoding="application/x-tex">
\{a_x, b_x, k_t\} \rightarrow \{a_x - c b_x, b_x, k_t + c\}.
</annotation></semantics></math></p>
<p>To address this issue and ensure model identifiability, Lee and Carter (1992) imposed the following constraints:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><munderover><mo>∑</mo><mrow><mi>t</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></munderover><msub><mi>k</mi><mi>t</mi></msub><mo>=</mo><mn>0</mn><mo>,</mo></mrow><annotation encoding="application/x-tex">
\sum_{t=1}^{n} k_t = 0,
</annotation></semantics></math></p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><munderover><mo>∑</mo><mrow><mi>x</mi><mo>=</mo><msub><mi>x</mi><mn>1</mn></msub></mrow><msub><mi>x</mi><mi>p</mi></msub></munderover><msub><mi>b</mi><mi>x</mi></msub><mo>=</mo><mn>1</mn><mi>.</mi></mrow><annotation encoding="application/x-tex">
\sum_{x=x_1}^{x_p} b_x = 1.
</annotation></semantics></math></p>
<p>These constraints normalize the model, ensuring that <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mi>t</mi></msub><annotation encoding="application/x-tex">k_t</annotation></semantics></math> is centered and that the age-specific impact <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>b</mi><mi>x</mi></msub><annotation encoding="application/x-tex">b_x</annotation></semantics></math> is appropriately scaled.</p>
</section><section class="level3"><h4 id="adjusting-and-forecasting-k_t">Adjusting and Forecasting <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mi>t</mi></msub><annotation encoding="application/x-tex">k_t</annotation></semantics></math><a class="anchor" aria-label="anchor" href="#adjusting-and-forecasting-k_t"></a>
</h4>
<p>In addition to the above constraints, the Lee-Carter method adjusts <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mi>t</mi></msub><annotation encoding="application/x-tex">k_t</annotation></semantics></math> by refitting it to the observed total number of deaths. This adjustment process gives more weight to ages with higher mortality rates, effectively counterbalancing the impact of the logarithmic transformation of the mortality rates.</p>
<p>The adjusted <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mi>t</mi></msub><annotation encoding="application/x-tex">k_t</annotation></semantics></math> is then extrapolated using time series models, particularly ARIMA models. <span class="citation" data-cites="lee1992">Lee and Carter (<a href="#ref-lee1992" role="doc-biblioref">1992</a>)</span> utilized a random walk with drift (RWD) model for this purpose, which is expressed as:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>k</mi><mi>t</mi></msub><mo>=</mo><msub><mi>k</mi><mrow><mi>t</mi><mo>−</mo><mn>1</mn></mrow></msub><mo>+</mo><mi>d</mi><mo>+</mo><msub><mi>e</mi><mi>t</mi></msub><mo>,</mo></mrow><annotation encoding="application/x-tex">
k_t = k_{t-1} + d + e_t,
</annotation></semantics></math></p>
<p>where:</p>
<ul>
<li>
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>d</mi><annotation encoding="application/x-tex">d</annotation></semantics></math> represents the drift parameter, measuring the average annual change in the series.</li>
<li>
<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>e</mi><mi>t</mi></msub><annotation encoding="application/x-tex">e_t</annotation></semantics></math> is an uncorrelated error term.</li>
</ul>
<p>The random walk with drift (RWD) model has proven to provide satisfactory results in various applications, as noted by subsequent studies (<span class="citation" data-cites="tuljapurkar2000">Tuljapurkar, Li, and Boe (<a href="#ref-tuljapurkar2000" role="doc-biblioref">2000</a>)</span>; <span class="citation" data-cites="lee2001">Lee and Miller (<a href="#ref-lee2001" role="doc-biblioref">2001</a>)</span>; <span class="citation" data-cites="lazar2005">Lazar and Denuit (<a href="#ref-lazar2005" role="doc-biblioref">2005</a>)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lc.male</span> <span class="op">&lt;-</span> <span class="fu">lca</span><span class="op">(</span><span class="va">france</span>, series<span class="op">=</span><span class="st">"male"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">lc.male</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="mortality_vignette_files/figure-html/unnamed-chunk-1-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="justify">
<p>Once the Lee-Carter model is fitted, actuaries can utilize it to forecast future mortality rates, a critical step in pricing life insurance products, setting aside reserves, and estimating liabilities in pension schemes. The three panels in the plot effectively illustrate the main effects and interaction terms that the Lee-Carter model captures:</p>
<ol type="1">
<li><p><strong><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>a</mi><mi>x</mi></msub><annotation encoding="application/x-tex">a_x</annotation></semantics></math> - Main Effects (Age-Specific Average Mortality Pattern)</strong>: This panel displays the general mortality pattern across different ages. The characteristic “U-shape” is evident, with higher mortality rates during infancy, a decline through early adulthood, and a steady increase with advancing age. This pattern aligns with the general mortality trends observed in many populations, providing a foundational understanding of age-specific mortality behavior.</p></li>
<li><p><strong><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>b</mi><mi>x</mi></msub><annotation encoding="application/x-tex">b_x</annotation></semantics></math> - Age-Specific Sensitivity to the Mortality Index</strong>: This panel highlights the sensitivity of each age group to changes in the overall mortality index $ k_t $. Younger age groups exhibit higher sensitivity, which gradually decreases with age. This implies that fluctuations in mortality, whether improvements or deteriorations, have a more pronounced impact on younger individuals compared to older ones.</p></li>
<li><p><strong><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mi>t</mi></msub><annotation encoding="application/x-tex">k_t</annotation></semantics></math> - Time Index of Mortality</strong>: The bottom panel traces the changes in mortality over time, capturing the influence of historical events and broader trends. The noticeable “humps” in the early 20th century correspond to periods of war and other significant disruptions. The long-term decline in <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mi>t</mi></msub><annotation encoding="application/x-tex">k_t</annotation></semantics></math> reflects overall improvements in mortality rates over the years, indicative of advancements in healthcare, living conditions, and public health interventions.</p></li>
</ol>
<p>These components are essential for forecasting future mortality rates, a process facilitated by the <code>forecast()</code> function from the <code>forecast</code> package. The output of the Lee-Carter model, particularly the forecasted <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mi>t</mi></msub><annotation encoding="application/x-tex">k_t</annotation></semantics></math>, enables actuaries to project future mortality rates, which is crucial for financial planning and decision-making in life insurance and pension schemes.</p>
<p>These visualizations are invaluable tools for actuaries, aiding in the communication of mortality trends to stakeholders, regulators, and policymakers. By presenting the projections in a clear and transparent manner, actuaries ensure that their forecasts are based on robust statistical analysis, thereby supporting informed decision-making.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Perform the forecast</span></span>
<span><span class="va">forecast.lc.male</span> <span class="op">&lt;-</span> <span class="fu">forecast</span><span class="op">(</span><span class="va">lc.male</span>, h <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span></code></pre></div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code for plotting the Lee-Carter components</summary><div class="sourceCode cell-code" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Plot the forecast components</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">forecast.lc.male</span>, plot.type <span class="op">=</span> <span class="st">"component"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div id="fig-component-lee-male" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-component-lee-male-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 2: Forecast Components for Male Mortality
</figcaption><div aria-describedby="fig-component-lee-male-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mortality_vignette_files/figure-html/fig-component-lee-male-1.png" width="768">
</div>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code for plotting the Lee-Carter forecast</summary><div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Plot the historical mortality data with adjusted line width and color</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">france</span>, series <span class="op">=</span> <span class="st">"male"</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">13</span>, <span class="fl">2</span><span class="op">)</span>, lty <span class="op">=</span> <span class="fl">2</span>, lwd <span class="op">=</span> <span class="fl">1</span>, col <span class="op">=</span> <span class="st">"#440154FF"</span>,</span>
<span>     main <span class="op">=</span> <span class="st">""</span>,</span>
<span>     ylab <span class="op">=</span> <span class="st">"Log-Mortality Rate"</span>, xlab <span class="op">=</span> <span class="st">"Age"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Add the forecast lines with distinct color and line type</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html" class="external-link">lines</a></span><span class="op">(</span><span class="va">forecast.lc.male</span>, col <span class="op">=</span> <span class="st">"#1E88E5"</span>, lty <span class="op">=</span> <span class="fl">1</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Add a legend to distinguish between observed and forecasted data</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html" class="external-link">legend</a></span><span class="op">(</span><span class="st">"bottomright"</span>, legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"Observed Data"</span>, <span class="st">"Forecast"</span><span class="op">)</span>,</span>
<span>       col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"#440154FF"</span>, <span class="st">"#1E88E5"</span><span class="op">)</span>, lty <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">)</span>, lwd <span class="op">=</span> <span class="fl">2</span>, cex <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div id="fig-forcast-lee-male" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-forcast-lee-male-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 3: Lee-Carter Method: Observed and Forecasted (next 20 years) Male Log-Mortality Rates in France
</figcaption><div aria-describedby="fig-forcast-lee-male-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mortality_vignette_files/figure-html/fig-forcast-lee-male-1.png" width="768">
</div>
</figure>
</div>
</div>
</div>
</section><section class="level3"><h4 id="interpretation-of-the-plot">Interpretation of the Plot<a class="anchor" aria-label="anchor" href="#interpretation-of-the-plot"></a>
</h4>
<div class="justify">
<p>The plot displays the smoothed historical male death rates for France from 1900 to 2022, along with forecasted mortality rates. While the Lee-Carter model is a widely utilized tool in actuarial science, the results presented here raise concerns about the accuracy of its forecasts:</p>
<ul>
<li><p><strong>Observed Data (Black Dashed Line)</strong>: The historical mortality rates exhibit the characteristic “U-shape” pattern, with elevated mortality at infancy, reduced rates during early adulthood, and a steady increase with advancing age. However, the density of the black lines makes it challenging to discern specific trends, particularly among younger age groups, where subtle variations are easily obscured.</p></li>
<li><p><strong>Forecasted Data (Blue Line)</strong>: The forecasted mortality rates, depicted by the blue line, generally align with the overall trend of the observed data. However, these forecasts appear overly optimistic, projecting significantly lower future mortality rates than might be realistic. This discrepancy raises concerns about the model’s ability to accurately capture the complexity of future mortality trends, particularly in light of potential unforeseen events or structural changes in population health.</p></li>
<li><p><strong>Model Effectiveness</strong>: Although the Lee-Carter model effectively captures the historical trend of declining mortality rates, the forecasts generated here may be too “optimistic,” predicting unrealistically low mortality rates in the future. Such over-optimism in the forecasts could be misleading, potentially leading to an underestimation of future mortality risks. This poses a significant risk for actuarial practices, where accurate mortality projections are crucial for pricing, reserving, and long-term financial planning.</p></li>
</ul>
<p>Given these observations, it is essential to critically evaluate the model’s assumptions and consider the potential limitations of the Lee-Carter model in forecasting long-term mortality trends. Supplementing this analysis with alternative models or incorporating scenario testing could provide a more comprehensive understanding of future mortality risks.</p>
</div>
</section><section class="level3"><h4 id="key-takeaways">Key Takeaways<a class="anchor" aria-label="anchor" href="#key-takeaways"></a>
</h4>
<div class="justify">
<ul>
<li><p>The Lee-Carter model serves as a foundational framework for mortality forecasting. However, the results presented here suggest that the model may be overly optimistic, potentially underestimating future death rates.</p></li>
<li><p>To enhance the reliability and practical applicability of these forecasts, it is essential to revisit the model’s assumptions and explore alternative approaches or adjustments, particularly in relation to outliers that might be skewing the results.</p></li>
<li><p>To address these concerns, we will implement the <code>HUrob</code> method, which is specifically designed to handle outliers that could be influencing the model’s forecasts. These outliers may be contributing to the overly optimistic predictions, and <code>HUrob</code> provides a robust mechanism to adjust for these anomalies, thereby producing more accurate and reliable forecasts.</p></li>
</ul>
<p>This interpretation underscores the importance of critically evaluating both the model and its output, ensuring that the forecasts are not only statistically robust but also aligned with realistic expectations for future mortality trends. By incorporating methods like <code>HUrob</code>, we can better manage the influence of outliers and improve the accuracy of our mortality projections, ultimately leading to more reliable actuarial decisions.</p>
</div>
</section></section></section><section class="section level2"><h2 id="outlier-detection-with-rainbow-package">Outlier Detection with Rainbow package<a class="anchor" aria-label="anchor" href="#outlier-detection-with-rainbow-package"></a>
</h2>
<p>We will proceed as if unaware of the historical impact of wars, preparing the data as functional data to apply the <code>fboxplot</code> method. The <code>fboxplot</code> function generates a functional boxplot, which extends the traditional boxplot concept to functional data. This method provides a comprehensive summary of the distribution of mortality rate curves by:</p>
<ul>
<li>
<strong>Central Region</strong>: Identifying the most typical curve, representing the central tendency of the data.</li>
<li>
<strong>Variability</strong>: Highlighting the variability among the mortality curves, which is depicted as shaded regions. These regions indicate the spread of the data and help visualize how mortality rates fluctuate across different years or age groups.</li>
<li>
<strong>Outliers</strong>: Detecting potential outliers, represented by curves that fall outside the shaded envelope. These outliers may correspond to unusual years or age groups with mortality rates that significantly deviate from the norm, potentially due to historical events like wars or data anomalies.</li>
</ul>
<p>By applying the <code>fboxplot</code> method, we can effectively identify and analyze these deviations, enabling a more nuanced understanding of the data. This approach allows for the detection of unusual patterns that may require further investigation or adjustment in the modeling process, particularly in cases where historical events or anomalies have a significant impact on mortality trends.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># filtering age &lt;= 100 and years &gt;= 1880</span></span>
<span><span class="va">year_filter</span> <span class="op">&lt;-</span> <span class="va">france</span><span class="op">$</span><span class="va">year</span> <span class="op">&gt;=</span> <span class="fl">1880</span></span>
<span><span class="va">filtered_years</span> <span class="op">&lt;-</span> <span class="va">france</span><span class="op">$</span><span class="va">year</span><span class="op">[</span><span class="va">year_filter</span><span class="op">]</span></span>
<span><span class="va">filtered_mortality_rates</span> <span class="op">&lt;-</span> <span class="va">france</span><span class="op">$</span><span class="va">rate</span><span class="op">$</span><span class="va">male</span><span class="op">[</span>, <span class="va">year_filter</span><span class="op">]</span></span>
<span></span>
<span><span class="va">age_filter</span> <span class="op">&lt;-</span> <span class="va">france</span><span class="op">$</span><span class="va">age</span> <span class="op">&lt;=</span> <span class="fl">100</span></span>
<span><span class="va">filtered_ages</span> <span class="op">&lt;-</span> <span class="va">france</span><span class="op">$</span><span class="va">age</span><span class="op">[</span><span class="va">age_filter</span><span class="op">]</span></span>
<span><span class="va">log_mortality_rates</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">log</a></span><span class="op">(</span><span class="va">filtered_mortality_rates</span><span class="op">[</span><span class="va">age_filter</span>, <span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Create a Functional Data Set (fds) object for the fboxplot</span></span>
<span><span class="va">log_mortality_fds</span> <span class="op">&lt;-</span> <span class="fu">fds</span><span class="op">(</span>x <span class="op">=</span> <span class="va">filtered_ages</span>, y <span class="op">=</span> <span class="va">log_mortality_rates</span><span class="op">)</span></span></code></pre></div>
</div>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-1-1">Functional boxplot</a></li>
<li><a href="#tabset-1-2">Functional bagplot</a></li>
</ul>
<ul class="nav nav-tabs" id="NA" role="tablist"><li role="presentation" class="nav-item"><button data-bs-toggle="tab" data-bs-target="#NA" id="NA-tab" type="button" role="tab" aria-controls="NA" aria-selected="true" class="active nav-link">
<div class="cell">
<details class="code-fold"><summary>Code for the following functional HDR boxplot</summary><div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">fboxplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">log_mortality_fds</span>,</span>
<span>         na.rm <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>         plot.type <span class="op">=</span> <span class="st">"functional"</span>,   <span class="co"># For a functional boxplot</span></span>
<span>         type <span class="op">=</span> <span class="st">"bag"</span>,               <span class="co"># For an bag boxplot</span></span>
<span>         alpha <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">0.05</span>, <span class="fl">0.5</span><span class="op">)</span>,       <span class="co"># Coverage level</span></span>
<span>         projmethod <span class="op">=</span> <span class="st">"PCAproj"</span>,     <span class="co"># Use PCA projection method</span></span>
<span>         factor <span class="op">=</span> <span class="fl">1.96</span>,              <span class="co"># Factor for the outer region</span></span>
<span>         xlab <span class="op">=</span> <span class="st">"Age"</span>,               </span>
<span>         ylab <span class="op">=</span> <span class="st">"Log-Mortality Rate"</span>,</span>
<span>         shadecols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/gray.html" class="external-link">gray</a></span><span class="op">(</span><span class="op">(</span><span class="fl">9</span><span class="op">:</span><span class="fl">1</span><span class="op">)</span><span class="op">/</span><span class="fl">10</span><span class="op">)</span>, <span class="co"># Colors for shaded regions</span></span>
<span>         pointcol <span class="op">=</span> <span class="fl">1</span>,               <span class="co"># Color of points (outliers and mode)</span></span>
<span>         plotlegend <span class="op">=</span> <span class="cn">TRUE</span>,         </span>
<span>         legendpos <span class="op">=</span> <span class="st">"bottomright"</span>,  </span>
<span>         ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>                  </span></code></pre></div>
</details><div class="cell-output-display">
<div id="fig-fboxplot-functional-mortality" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-fboxplot-functional-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 4: Functional Boxplot of Log-Mortality Rates in France
</figcaption><div aria-describedby="fig-fboxplot-functional-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mortality_vignette_files/figure-html/fig-fboxplot-functional-mortality-1.png" width="768">
</div>
</figure>
</div>
</div>
</div>
<p>The functional HDR boxplot illustrates the distribution of log mortality rates across various years during and after the World Wars. The shaded regions in the plot represent the central 50% and 95% of the data, effectively highlighting the typical mortality patterns observed during these periods.</p>
<p>The year 1919 is identified as an outlier, displaying higher-than-expected mortality rates despite occurring after World War I. This anomaly could be attributed to the lingering effects of the war, the 1918 influenza pandemic, or other socio-economic disruptions. This observation underscores the fact that even years outside of direct wartime can exhibit atypical mortality patterns due to the residual effects of conflict or other external factors.</p>
<p>The periods 1914-1918 (WWI) and 1940-1945 (WWII) are characterized by elevated mortality rates, particularly among younger and middle-aged populations, reflecting the direct impact of these conflicts on the population.</p>
<p>This analysis demonstrates the utility of functional HDR boxplots in effectively identifying outliers and typical patterns in mortality data, providing valuable insights into how significant historical events and their aftermath can shape mortality trends.</p>
</button></li></ul>
<div class="tab-content"><div class="active  tab-pane" id="NA" role="tabpanel" aria-labelledby="NA-tab">

<div id="tabset-1-2">
<div class="cell">
<details class="code-fold"><summary>Code for the following functional HDR boxplot</summary><div class="sourceCode cell-code" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">fboxplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">log_mortality_fds</span>,</span>
<span>         na.rm <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>         plot.type <span class="op">=</span> <span class="st">"bivariate"</span>,   <span class="co"># For a bivariate boxplot</span></span>
<span>         type <span class="op">=</span> <span class="st">"bag"</span>,               <span class="co"># For an bag boxplot</span></span>
<span>         alpha <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">0.05</span>, <span class="fl">0.5</span><span class="op">)</span>,       <span class="co"># Coverage level</span></span>
<span>         projmethod <span class="op">=</span> <span class="st">"PCAproj"</span>,     <span class="co"># Use PCA projection method</span></span>
<span>         factor <span class="op">=</span> <span class="fl">1.96</span>,              <span class="co"># Factor for the outer region</span></span>
<span>         xlab <span class="op">=</span> <span class="st">"Age"</span>,               </span>
<span>         ylab <span class="op">=</span> <span class="st">"Log-Mortality Rate"</span>,</span>
<span>         shadecols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/gray.html" class="external-link">gray</a></span><span class="op">(</span><span class="op">(</span><span class="fl">9</span><span class="op">:</span><span class="fl">1</span><span class="op">)</span><span class="op">/</span><span class="fl">10</span><span class="op">)</span>, <span class="co"># Colors for shaded regions</span></span>
<span>         pointcol <span class="op">=</span> <span class="fl">1</span>,               <span class="co"># Color of points (outliers and mode)</span></span>
<span>         plotlegend <span class="op">=</span> <span class="cn">TRUE</span>,         </span>
<span>         legendpos <span class="op">=</span> <span class="st">"bottomright"</span>,  </span>
<span>         ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>                  </span></code></pre></div>
</details><div class="cell-output-display">
<div id="fig-fboxplot-bivariate-mortality" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-fboxplot-bivariate-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 5: Bivariate Boxplot of Log-Mortality Rates in France
</figcaption><div aria-describedby="fig-fboxplot-bivariate-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mortality_vignette_files/figure-html/fig-fboxplot-bivariate-mortality-1.png" width="768">
</div>
</figure>
</div>
</div>
</div>
</div>
</div></div>
</div>
</section><section class="section level2"><h2 id="robust-hyndmanullah-hurob-method">Robust Hyndman–Ullah (HUrob) Method<a class="anchor" aria-label="anchor" href="#robust-hyndmanullah-hurob-method"></a>
</h2>
<p>Outliers, or unusual data points, can seriously affect the performance of modeling and forecasting. The <code>HUrob</code> method is designed to eliminate their effect. This method utilizes the reflection-based principal component analysis (RAPCA) algorithm of <span class="citation" data-cites="hubert2002fast">Hubert, Rousseeuw, and Verboven (<a href="#ref-hubert2002fast" role="doc-biblioref">2002</a>)</span> to obtain projection-pursuit estimates of principal components and their associated scores. The integrated squared error provides a measure of the accuracy of the principal component approximation for each year (<span class="citation" data-cites="hyndman2007robust">Hyndman and Ullah (<a href="#ref-hyndman2007robust" role="doc-biblioref">2007</a>)</span>). Outlying years result in a larger integrated squared error than the critical value obtained by assuming normality of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>ϵ</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">\epsilon_t(x)</annotation></semantics></math> (see <span class="citation" data-cites="hyndman2007robust">Hyndman and Ullah (<a href="#ref-hyndman2007robust" role="doc-biblioref">2007</a>)</span> for details). By assigning zero weight to outliers, the <code>HUrob</code> method can then be used to model and forecast mortality rates without the possible influence of outliers.</p>
<section class="level2"><h3 id="how-the-hurob-method-works">How the <code>HUrob</code> Method Works<a class="anchor" aria-label="anchor" href="#how-the-hurob-method-works"></a>
</h3>
<p>The <code>HUrob</code> method uses an advanced technique called reflection-based principal component analysis (RAPCA). This technique helps to identify the main patterns in the data while filtering out those outliers that could lead to inaccurate predictions.</p>
<p>Here’s a simplified explanation:</p>
<ul>
<li>
<strong>Principal Components</strong>: Think of these as the main patterns in your data. The method tries to capture these patterns and ignore the noise or outliers.</li>
<li>
<strong>Outliers</strong>: These are unusual data points that don’t fit the general pattern. If left unchecked, they can distort the model’s predictions.</li>
</ul>
<p>By assigning zero weight to outliers, the <code>HUrob</code> method effectively ignores these problematic data points, making the model’s predictions more robust and trustworthy.</p>
<p>Using the functional data analysis paradigm of <span class="citation" data-cites="ramsay2005">Ramsay and Silverman (<a href="#ref-ramsay2005" role="doc-biblioref">2005</a>)</span>, <span class="citation" data-cites="hyndman2007robust">Hyndman and Ullah (<a href="#ref-hyndman2007robust" role="doc-biblioref">2007</a>)</span> proposed a nonparametric method for modeling and forecasting log mortality rates. This approach extends the Lee-Carter (LC) method in four ways:</p>
<ul>
<li>The log mortality rates are smoothed prior to modeling.</li>
<li>Functional principal components analysis (FPCA) is used.</li>
<li>More than one principal component is used in forecasting.</li>
<li>The forecasting models for the principal component scores are typically more complex than the RWD model.</li>
</ul>
<p>The log mortality rates are smoothed using penalized regression splines. To emphasize that age, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>x</mi><annotation encoding="application/x-tex">x</annotation></semantics></math>, is now considered a continuous variable, we write <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>m</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">m_t(x)</annotation></semantics></math> to represent mortality rates for age <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>x</mi><mo>∈</mo><mrow><mo stretchy="true" form="prefix">[</mo><msub><mi>x</mi><mn>1</mn></msub><mo>,</mo><msub><mi>x</mi><mi>p</mi></msub><mo stretchy="true" form="postfix">]</mo></mrow></mrow><annotation encoding="application/x-tex">x \in [x_1, x_p]</annotation></semantics></math> in year <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>t</mi><annotation encoding="application/x-tex">t</annotation></semantics></math>. We then define <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>z</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><mo>log</mo><msub><mi>m</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">z_t(x) = \log m_t(x)</annotation></semantics></math> and write:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>z</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><msub><mi>x</mi><mi>i</mi></msub><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><msub><mi>f</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><msub><mi>x</mi><mi>i</mi></msub><mo stretchy="true" form="postfix">)</mo></mrow><mo>+</mo><msub><mi>σ</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><msub><mi>x</mi><mi>i</mi></msub><mo stretchy="true" form="postfix">)</mo></mrow><msub><mi>ϵ</mi><mrow><mi>t</mi><mo>,</mo><mi>i</mi></mrow></msub><mo>,</mo><mspace width="1.0em"></mspace><mi>i</mi><mo>=</mo><mn>1</mn><mo>,</mo><mi>…</mi><mo>,</mo><mi>p</mi><mo>,</mo><mspace width="1.0em"></mspace><mi>t</mi><mo>=</mo><mn>1</mn><mo>,</mo><mi>…</mi><mo>,</mo><mi>n</mi><mo>,</mo><mspace width="0.222em"></mspace><mrow><mo stretchy="true" form="prefix">(</mo><mn>2</mn><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">
z_t(x_i) = f_t(x_i) + \sigma_t(x_i) \epsilon_{t,i}, \quad i = 1, \dots, p, \quad t = 1, \dots, n,\ (2)
</annotation></semantics></math></p>
<p>where <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>f</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><msub><mi>x</mi><mi>i</mi></msub><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">f_t(x_i)</annotation></semantics></math> denotes a smooth function of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>x</mi><annotation encoding="application/x-tex">x</annotation></semantics></math> as before; <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>σ</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><msub><mi>x</mi><mi>i</mi></msub><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">\sigma_t(x_i)</annotation></semantics></math> allows the amount of noise to vary with <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>x</mi><mi>i</mi></msub><annotation encoding="application/x-tex">x_i</annotation></semantics></math> in year <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>t</mi><annotation encoding="application/x-tex">t</annotation></semantics></math>, thus rectifying the assumption of homoskedastic error in the LC model; and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>ϵ</mi><mrow><mi>t</mi><mo>,</mo><mi>i</mi></mrow></msub><annotation encoding="application/x-tex">\epsilon_{t,i}</annotation></semantics></math> is an independent and identically distributed standard normal random variable.</p>
<p>Given continuous age <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>x</mi><annotation encoding="application/x-tex">x</annotation></semantics></math>, functional principal components analysis (FPCA) is used in the decomposition. The set of age-specific mortality curves is decomposed into orthogonal functional principal components and their uncorrelated principal component scores. That is:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>f</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><mi>a</mi><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>+</mo><munderover><mo>∑</mo><mrow><mi>j</mi><mo>=</mo><mn>1</mn></mrow><mi>J</mi></munderover><msub><mi>b</mi><mi>j</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><msub><mi>k</mi><mrow><mi>t</mi><mo>,</mo><mi>j</mi></mrow></msub><mo>+</mo><msub><mi>e</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>,</mo></mrow><annotation encoding="application/x-tex">
f_t(x) = a(x) + \sum_{j=1}^{J} b_j(x) k_{t,j} + e_t(x),
</annotation></semantics></math></p>
<p>where <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>a</mi><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">a(x)</annotation></semantics></math> is the mean function estimated by <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mover><mi>a</mi><mo accent="true">̂</mo></mover><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><mfrac><mn>1</mn><mi>n</mi></mfrac><msubsup><mo>∑</mo><mrow><mi>t</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></msubsup><msub><mi>f</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">\hat{a}(x) = \frac{1}{n} \sum_{t=1}^{n} f_t(x)</annotation></semantics></math>; <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="false" form="prefix">{</mo><msub><mi>b</mi><mn>1</mn></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>,</mo><mi>…</mi><mo>,</mo><msub><mi>b</mi><mi>J</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo stretchy="false" form="postfix">}</mo></mrow><annotation encoding="application/x-tex">\{b_1(x), \dots, b_J(x)\}</annotation></semantics></math> is a set of the first <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>J</mi><annotation encoding="application/x-tex">J</annotation></semantics></math> functional principal components; <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mo stretchy="false" form="prefix">{</mo><msub><mi>k</mi><mrow><mi>t</mi><mo>,</mo><mn>1</mn></mrow></msub><mo>,</mo><mi>…</mi><mo>,</mo><msub><mi>k</mi><mrow><mi>t</mi><mo>,</mo><mi>J</mi></mrow></msub><mo stretchy="false" form="postfix">}</mo></mrow><annotation encoding="application/x-tex">\{k_{t,1}, \dots, k_{t,J}\}</annotation></semantics></math> is a set of uncorrelated principal component scores; <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>e</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">e_t(x)</annotation></semantics></math> is the residual function with mean zero; and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>J</mi><mo>&lt;</mo><mi>n</mi></mrow><annotation encoding="application/x-tex">J &lt; n</annotation></semantics></math> is the number of principal components used. Note that we use <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>a</mi><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">a(x)</annotation></semantics></math> rather than <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>a</mi><mi>x</mi></msub><annotation encoding="application/x-tex">a_x</annotation></semantics></math> to emphasize that <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>x</mi><annotation encoding="application/x-tex">x</annotation></semantics></math> is treated as a continuous variable.</p>
<p>Multiple principal components are used because the additional components capture non-random patterns that are not explained by the first principal component (<span class="citation" data-cites="booth2002">Booth, Maindonald, and Smith (<a href="#ref-booth2002" role="doc-biblioref">2002</a>)</span>; <span class="citation" data-cites="renshaw2003">Renshaw and Haberman (<a href="#ref-renshaw2003" role="doc-biblioref">2003</a>)</span>; <span class="citation" data-cites="koissi2006">Koissi, Shapiro, and Högnäs (<a href="#ref-koissi2006" role="doc-biblioref">2006</a>)</span>). <span class="citation" data-cites="hyndman2007robust">Hyndman and Ullah (<a href="#ref-hyndman2007robust" role="doc-biblioref">2007</a>)</span> found <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>J</mi><mo>=</mo><mn>6</mn></mrow><annotation encoding="application/x-tex">J = 6</annotation></semantics></math> to be larger than the number of components actually required to produce white noise residuals, and this is the default value. The conditions for the existence and uniqueness of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mrow><mi>t</mi><mo>,</mo><mi>j</mi></mrow></msub><annotation encoding="application/x-tex">k_{t,j}</annotation></semantics></math> are discussed by Cardot, Ferraty &amp; Sarda (2003).</p>
<p>Although <span class="citation" data-cites="lee1992">Lee and Carter (<a href="#ref-lee1992" role="doc-biblioref">1992</a>)</span> did not rule out the possibility of a more complex time series model for the <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mi>t</mi></msub><annotation encoding="application/x-tex">k_t</annotation></semantics></math> series, in practice, an RWD model has typically been employed in the LC method. For higher-order principal components, which are orthogonal by definition to the first component, other time series models arise for the principal component scores. For all components, the <code>HUrob</code> method selects the optimal time series model using standard model-selection procedures (e.g., AIC). By conditioning on the observed data <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>I</mi><mo>=</mo><mo stretchy="false" form="prefix">{</mo><msub><mi>z</mi><mn>1</mn></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>,</mo><mi>…</mi><mo>,</mo><msub><mi>z</mi><mi>n</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo stretchy="false" form="postfix">}</mo></mrow><annotation encoding="application/x-tex">I = \{z_1(x), \dots, z_n(x)\}</annotation></semantics></math> and the set of functional principal components <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>B</mi><mo>=</mo><mo stretchy="false" form="prefix">{</mo><msub><mi>b</mi><mn>1</mn></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>,</mo><mi>…</mi><mo>,</mo><msub><mi>b</mi><mi>J</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo stretchy="false" form="postfix">}</mo></mrow><annotation encoding="application/x-tex">B = \{b_1(x), \dots, b_J(x)\}</annotation></semantics></math>, the <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>h</mi><annotation encoding="application/x-tex">h</annotation></semantics></math>-step-ahead forecast of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>z</mi><mrow><mi>n</mi><mo>+</mo><mi>h</mi></mrow></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">z_{n+h}(x)</annotation></semantics></math> can be obtained by:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mover><mi>z</mi><mo accent="true">̂</mo></mover><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo stretchy="false" form="prefix">|</mo><mi>n</mi></mrow></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><mi>E</mi><mrow><mo stretchy="true" form="prefix">[</mo><msub><mi>z</mi><mrow><mi>n</mi><mo>+</mo><mi>h</mi></mrow></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo stretchy="false" form="prefix">|</mo><mi>I</mi><mo>,</mo><mi>B</mi><mo stretchy="true" form="postfix">]</mo></mrow><mo>=</mo><mover><mi>a</mi><mo accent="true">̂</mo></mover><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>+</mo><munderover><mo>∑</mo><mrow><mi>j</mi><mo>=</mo><mn>1</mn></mrow><mi>J</mi></munderover><msub><mi>b</mi><mi>j</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><msub><mover><mi>k</mi><mo accent="true">̂</mo></mover><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo stretchy="false" form="prefix">|</mo><mi>n</mi><mo>,</mo><mi>j</mi></mrow></msub><mo>,</mo></mrow><annotation encoding="application/x-tex">
\hat{z}_{n+h|n}(x) = E[z_{n+h}(x) | I, B] = \hat{a}(x) + \sum_{j=1}^{J} b_j(x) \hat{k}_{n+h|n,j},
</annotation></semantics></math></p>
<p>where <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mover><mi>k</mi><mo accent="true">̂</mo></mover><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo stretchy="false" form="prefix">|</mo><mi>n</mi><mo>,</mo><mi>j</mi></mrow></msub><annotation encoding="application/x-tex">\hat{k}_{n+h|n,j}</annotation></semantics></math> denotes the <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>h</mi><annotation encoding="application/x-tex">h</annotation></semantics></math>-step-ahead forecast of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>k</mi><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo>,</mo><mi>j</mi></mrow></msub><annotation encoding="application/x-tex">k_{n+h,j}</annotation></semantics></math> using a univariate time series model, such as the optimal ARIMA model selected by the automatic algorithm of <span class="citation" data-cites="hyndman2008">Hyndman et al. (<a href="#ref-hyndman2008" role="doc-biblioref">2008</a>)</span>, or an exponential smoothing state space model (<span class="citation" data-cites="hyndman2008">Hyndman et al. (<a href="#ref-hyndman2008" role="doc-biblioref">2008</a>)</span>).</p>
<p>Because of the orthogonality of all components, it is easy to derive the forecast variance as:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mover><mi>v</mi><mo accent="true">̂</mo></mover><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo stretchy="false" form="prefix">|</mo><mi>n</mi></mrow></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><mtext mathvariant="normal">var</mtext><mrow><mo stretchy="true" form="prefix">[</mo><msub><mi>z</mi><mrow><mi>n</mi><mo>+</mo><mi>h</mi></mrow></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo stretchy="false" form="prefix">|</mo><mi>I</mi><mo>,</mo><mi>B</mi><mo stretchy="true" form="postfix">]</mo></mrow><mo>=</mo><msubsup><mi>σ</mi><mi>a</mi><mn>2</mn></msubsup><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>+</mo><munderover><mo>∑</mo><mrow><mi>j</mi><mo>=</mo><mn>1</mn></mrow><mi>J</mi></munderover><msubsup><mi>b</mi><mi>j</mi><mn>2</mn></msubsup><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><msub><mi>u</mi><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo stretchy="false" form="prefix">|</mo><mi>n</mi><mo>,</mo><mi>j</mi></mrow></msub><mo>+</mo><mi>v</mi><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>+</mo><msubsup><mi>σ</mi><mi>t</mi><mn>2</mn></msubsup><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>,</mo></mrow><annotation encoding="application/x-tex">
\hat{v}_{n+h|n}(x) = \text{var}[z_{n+h}(x) | I, B] = \sigma^2_a(x) + \sum_{j=1}^{J} b_j^2(x) u_{n+h|n,j} + v(x) + \sigma^2_t(x),
</annotation></semantics></math></p>
<p>where <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msubsup><mi>σ</mi><mi>a</mi><mn>2</mn></msubsup><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">\sigma^2_a(x)</annotation></semantics></math> is the variance of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mover><mi>a</mi><mo accent="true">̂</mo></mover><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">\hat{a}(x)</annotation></semantics></math>; <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>u</mi><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo stretchy="false" form="prefix">|</mo><mi>n</mi><mo>,</mo><mi>j</mi></mrow></msub><annotation encoding="application/x-tex">u_{n+h|n,j}</annotation></semantics></math> is the variance of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>k</mi><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo>,</mo><mi>j</mi></mrow></msub><mo stretchy="false" form="prefix">|</mo><msub><mi>k</mi><mrow><mn>1</mn><mo>,</mo><mi>j</mi></mrow></msub><mo>,</mo><mi>…</mi><mo>,</mo><msub><mi>k</mi><mrow><mi>n</mi><mo>,</mo><mi>j</mi></mrow></msub></mrow><annotation encoding="application/x-tex">k_{n+h,j} | k_{1,j}, \dots, k_{n,j}</annotation></semantics></math> (obtained from the time series model); <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>v</mi><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">v(x)</annotation></semantics></math> is the variance of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>e</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">e_t(x)</annotation></semantics></math>; and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>σ</mi><mi>t</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">\sigma_t(x)</annotation></semantics></math> is defined in Equation (2). This expression is used to construct prediction intervals for future mortality rates in R.</p>
<section class="level3"><h4 id="key-enhancements-over-traditional-methods">Key Enhancements Over Traditional Methods<a class="anchor" aria-label="anchor" href="#key-enhancements-over-traditional-methods"></a>
</h4>
<p>The <code>HUrob</code> method improves upon traditional methods like the Lee-Carter (LC) model in several ways:</p>
<ul>
<li>
<strong>Smoothing</strong>: Log mortality rates are smoothed using techniques that stabilize the data, reducing the impact of random fluctuations.</li>
<li>
<strong>Principal Components Analysis (PCA)</strong>: Instead of relying on just one principal component, this method uses multiple components to capture more of the complexity in the data.</li>
<li>
<strong>Advanced Time Series Models</strong>: For predicting future trends, the <code>HUrob</code> method uses sophisticated models like ARIMA, which are more flexible and accurate than simpler models.</li>
</ul></section><section class="level3"><h4 id="putting-it-all-together">Putting It All Together<a class="anchor" aria-label="anchor" href="#putting-it-all-together"></a>
</h4>
<p>In simple terms, the <code>HUrob</code> method is a powerful tool for making more accurate predictions about future mortality rates. By carefully managing outliers and using advanced statistical techniques, this method helps actuaries and analysts make better-informed decisions, whether they are pricing life insurance products, setting aside reserves, or planning for the future.</p>
</section></section><section class="level2"><h3 id="conclusion">Conclusion<a class="anchor" aria-label="anchor" href="#conclusion"></a>
</h3>
<p>The <code>HUrob</code> method enhances mortality rate modeling by addressing the impact of outliers using reflection-based principal component analysis (RAPCA). By eliminating the influence of outliers, the method ensures more robust forecasts. The approach builds on the Lee-Carter model by smoothing log mortality rates, applying functional principal components analysis (FPCA), and using multiple principal components for forecasting. These components are modeled with more complex time series models, like ARIMA, instead of the simpler Random Walk with Drift (RWD). The method effectively captures mortality trends while accounting for varying noise across ages and years, leading to more accurate predictions with well-defined prediction intervals.</p>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-2-1">Fitting and forecasting HUrob</a></li>
<li><a href="#tabset-2-2">HUrob parameters</a></li>
</ul>
<ul class="nav nav-tabs" id="NA" role="tablist"><li role="presentation" class="nav-item"><button data-bs-toggle="tab" data-bs-target="#forecasting-and-reconstruction" id="forecasting-and-reconstruction-tab" type="button" role="tab" aria-controls="forecasting-and-reconstruction" aria-selected="true" class="active nav-link">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Apply the HUrob method using reflection-based PCA (RAPCA)</span></span>
<span><span class="va">fdm_france</span> <span class="op">&lt;-</span> <span class="fu">fdm</span><span class="op">(</span><span class="va">france</span>, series<span class="op">=</span><span class="st">"male"</span>, method<span class="op">=</span><span class="st">"rapca"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">france.fcast</span> <span class="op">&lt;-</span> <span class="fu">forecast</span><span class="op">(</span><span class="va">fdm_france</span>,<span class="fl">20</span><span class="op">)</span></span></code></pre></div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code for the following forecast</summary><div class="sourceCode cell-code" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Plot the observed and forecasted mortality rates</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">france</span>, series<span class="op">=</span><span class="st">"male"</span>,</span>
<span>     main <span class="op">=</span> <span class="st">""</span>,</span>
<span>     ylim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">10</span>, <span class="fl">0</span><span class="op">)</span>,</span>
<span>     col <span class="op">=</span> <span class="st">"#440154FF"</span>,</span>
<span>     lty<span class="op">=</span><span class="fl">2</span>,</span>
<span>     ylab <span class="op">=</span> <span class="st">"Log death rate"</span>, xlab <span class="op">=</span> <span class="st">"Age"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/lines.html" class="external-link">lines</a></span><span class="op">(</span><span class="va">france.fcast</span>, col <span class="op">=</span> <span class="st">"#1E88E5"</span>, lty <span class="op">=</span> <span class="fl">1</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Add a legend to distinguish between observed and forecasted data</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html" class="external-link">legend</a></span><span class="op">(</span><span class="st">"bottomright"</span>, legend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"Observed Data"</span>, <span class="st">"Forecast"</span><span class="op">)</span>,</span>
<span>       col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"#440154FF"</span>, <span class="st">"#1E88E5"</span><span class="op">)</span>, lty <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">)</span>, lwd <span class="op">=</span> <span class="fl">2</span>, cex <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div id="fig-plot-forecast-mortality" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-plot-forecast-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 6: HUrob Method: Log-Mortality rates Observed and Forecasted (next 20 years) in France
</figcaption><div aria-describedby="fig-plot-forecast-mortality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="mortality_vignette_files/figure-html/fig-plot-forecast-mortality-1.png" width="768">
</div>
</figure>
</div>
</div>
</div>
<p>The plot displays the log death rates for males in France from 1900 to 2022, across various age groups. The trends indicate that mortality rates have generally decreased over time, particularly at younger ages, but have started to rise again in older age groups.</p>
<p>This forecast appears to be less optimistic than the Lee-Carter projections. While it still indicates improvements in mortality at younger ages, the flattening and slight increase in death rates at older ages suggest a more realistic outlook. The forecast acknowledges the challenges in further reducing mortality, particularly among older populations, reflecting a more cautious and realistic approach to future mortality trends.</p>
</button></li></ul>
<div class="tab-content"><div class="active  tab-pane" id="forecasting-and-reconstruction" role="tabpanel" aria-labelledby="forecasting-and-reconstruction-tab">

<div id="tabset-2-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">models</span><span class="op">(</span><span class="va">france.fcast</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-- Coefficient 1 --
Series: xx[, i]
ARIMA(0,1,1) with drift

Coefficients:
         ma1   drift
      -0.177  -0.172
s.e.   0.098   0.094

sigma^2 = 1.61:  log likelihood = -199
AIC=405   AICc=405   BIC=413

-- Coefficient 2 --
Series: xx[, i]
ARIMA(1,1,1) with drift

Coefficients:
       ar1    ma1  drift
      0.35  -0.91  0.030
s.e.  0.11   0.06  0.013

sigma^2 = 0.806:  log likelihood = -158
AIC=323   AICc=324   BIC=335

-- Coefficient 3 --
Series: xx[, i]
ARIMA(2,1,2)

Coefficients:
       ar1    ar2    ma1   ma2
      0.39  -0.46  -1.04  0.64
s.e.  0.17   0.12   0.15  0.13

sigma^2 = 0.823:  log likelihood = -158
AIC=327   AICc=327   BIC=341

-- Coefficient 4 --
Series: xx[, i]
ARIMA(1,1,1)

Coefficients:
       ar1     ma1
      0.54  -0.946
s.e.  0.14   0.093

sigma^2 = 0.533:  log likelihood = -133
AIC=272   AICc=273   BIC=281

-- Coefficient 5 --
Series: xx[, i]
ARIMA(2,0,0) with zero mean

Coefficients:
        ar1    ar2
      0.547  0.192
s.e.  0.088  0.088

sigma^2 = 0.611:  log likelihood = -142
AIC=291   AICc=291   BIC=299

-- Coefficient 6 --
Series: xx[, i]
ARIMA(0,0,2) with zero mean

Coefficients:
       ma1    ma2
      0.28  0.257
s.e.  0.09  0.076

sigma^2 = 0.297:  log likelihood = -98
AIC=202   AICc=203   BIC=211</code></pre>
</div>
</div>
<div class="justify">
<p>The output summarizes various ARIMA models fitted to different components of the <code>HUrob</code> method.</p>
<ul>
<li><p><strong>Coefficient 1</strong>: ARIMA(0,1,1) with drift. This model reflects a weak negative moving average (ma1 = -0.177) and a negative drift (-0.172), suggesting a slight downward trend over time. The fit is moderate, with AIC = 405 and BIC = 413.</p></li>
<li><p><strong>Coefficient 2</strong>: ARIMA(1,1,1) with drift. This model captures stronger autocorrelation with ar1 = 0.35 and ma1 = -0.90. The drift term is positive (0.030), suggesting a slight upward trend. The fit improves with AIC = 323 and BIC = 335.</p></li>
<li><p><strong>Coefficient 3</strong>: ARIMA(2,1,2). A more complex model with two autoregressive and two moving average components. The mixed signs in the coefficients indicate intricate temporal dynamics. The model fits similarly to Coefficient 2, with AIC = 327 and BIC = 341.</p></li>
<li><p><strong>Coefficient 4</strong>: ARIMA(1,1,1). A simpler model with no drift, featuring moderate autocorrelation (ar1 = 0.54) and strong negative moving average (ma1 = -0.946). This model has a lower sigma^2 and improves in fit with AIC = 272 and BIC = 281.</p></li>
<li><p><strong>Coefficient 5</strong>: ARIMA(2,0,0). This model features autoregressive terms (ar1 = 0.547, ar2 = 0.192) and does not include a constant or drift, implying the process has no inherent trend. The residual variance is moderate (sigma^2 = 0.611), and the fit is reasonable with AIC = 291 and BIC = 299.</p></li>
<li><p><strong>Coefficient 6</strong>: ARIMA(0,0,2). This model includes two moving average terms (ma1 = 0.28, ma2 = 0.257) and also does not have a constant, suggesting no trend. It achieves the lowest residual variance (sigma^2 = 0.297) and provides a solid fit with AIC = 202 and BIC = 211.</p></li>
</ul>
<section class="level3"><h4 id="forecasting-and-reconstruction">Forecasting and Reconstruction</h4>
<p>The coefficients from these ARIMA models are used to forecast the principal component scores derived from the functional principal component analysis (FPCA). These scores represent the key patterns in the mortality data over time.</p>
<ul>
<li><p><strong>Forecasting</strong>: The ARIMA models, using the estimated coefficients (e.g., <code>ar1</code>, <code>ma1</code>, <code>drift</code>), predict future values of these scores.</p></li>
<li><p><strong>Reconstruction</strong>: The forecasted scores are then combined with the functional principal components to reconstruct future mortality rates using the formula:</p></li>
</ul>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mover><mi>z</mi><mo accent="true">̂</mo></mover><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo stretchy="false" form="prefix">|</mo><mi>n</mi></mrow></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><mover><mi>a</mi><mo accent="true">̂</mo></mover><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>+</mo><munderover><mo>∑</mo><mrow><mi>j</mi><mo>=</mo><mn>1</mn></mrow><mi>J</mi></munderover><msub><mi>b</mi><mi>j</mi></msub><mrow><mo stretchy="true" form="prefix">(</mo><mi>x</mi><mo stretchy="true" form="postfix">)</mo></mrow><msub><mover><mi>k</mi><mo accent="true">̂</mo></mover><mrow><mi>n</mi><mo>+</mo><mi>h</mi><mo stretchy="false" form="prefix">|</mo><mi>n</mi><mo>,</mo><mi>j</mi></mrow></msub></mrow><annotation encoding="application/x-tex">
\hat{z}_{n+h|n}(x) = \hat{a}(x) + \sum_{j=1}^{J} b_j(x) \hat{k}_{n+h|n,j}
</annotation></semantics></math></p>
<ul>
<li>
<strong>Final Output</strong>: This process yields the forecasted mortality rates, along with their associated variance and prediction intervals.</li>
</ul></section><section class="level3"><h4 id="practical-implications">Practical Implications<a class="anchor" aria-label="anchor" href="#practical-implications"></a>
</h4>
<p>These forecasts are essential for predicting future mortality trends across different age groups, providing a robust basis for actuarial analysis and decision-making.</p>
</section>
</div>
</div>
</div></div>
</div>
</section></section><section class="section level2"><h2 id="references">References<a class="anchor" aria-label="anchor" href="#references"></a>
</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<p>The date came from HMD. Human Mortality Database. Max Planck Institute for Demographic Research (Germany), University of California, Berkeley (USA), and French Institute for Demographic Studies (France). Available <a href="www.mortality.org">HMD</a>.</p>
<div id="ref-booth2002" class="csl-entry" role="listitem">
Booth, Heather, John Maindonald, and Len Smith. 2002. <span>“Applying Lee-Carter Under Conditions of Variable Mortality Decline.”</span> <em>Population Studies</em> 56 (3): 325–36.
</div>
<div id="ref-hubert2002fast" class="csl-entry" role="listitem">
Hubert, Mia, Peter J Rousseeuw, and Sabine Verboven. 2002. <span>“A Fast Method for Robust Principal Components with Applications to Chemometrics.”</span> <em>Chemometrics and Intelligent Laboratory Systems</em> 60 (1-2): 101–11.
</div>
<div id="ref-hyndman2008" class="csl-entry" role="listitem">
Hyndman, Rob J, Anne B Koehler, Ralph D Snyder, and Simone Grose. 2008. <span>“Forecasting with Exponential Smoothing: The State Space Approach.”</span> <em>Springer Series in Statistics</em>.
</div>
<div id="ref-hyndman2007robust" class="csl-entry" role="listitem">
Hyndman, Rob J, and Md Shahid Ullah. 2007. <span>“Robust Forecasting of Mortality and Fertility Rates: A Functional Data Approach.”</span> <em>Computational Statistics &amp; Data Analysis</em> 51 (10): 4942–56.
</div>
<div id="ref-koissi2006" class="csl-entry" role="listitem">
Koissi, Marie-Claire, Arnold F Shapiro, and George Högnäs. 2006. <span>“The State of the Art in the Lee–Carter Model.”</span> <em>Insurance: Mathematics and Economics</em> 38 (1): 2–23.
</div>
<div id="ref-lazar2005" class="csl-entry" role="listitem">
Lazar, Avner, and Michel Denuit. 2005. <span>“Robust Methods for Actuarial Applications.”</span> <em>Insurance: Mathematics and Economics</em> 36 (1): 1–21.
</div>
<div id="ref-lee1992" class="csl-entry" role="listitem">
Lee, Ronald D, and Lawrence R Carter. 1992. <span>“Modeling and Forecasting US Mortality.”</span> <em>Journal of the American Statistical Association</em> 87 (419): 659–71.
</div>
<div id="ref-lee2001" class="csl-entry" role="listitem">
Lee, Ronald D, and Timothy Miller. 2001. <span>“Evaluating the Performance of the Lee-Carter Method for Forecasting Mortality.”</span> <em>Demography</em> 38 (4): 537–49.
</div>
<div id="ref-ramsay2005" class="csl-entry" role="listitem">
Ramsay, James O, and Bernard W Silverman. 2005. <em>Functional Data Analysis</em>. Springer.
</div>
<div id="ref-renshaw2003" class="csl-entry" role="listitem">
Renshaw, Arthur E, and Steven Haberman. 2003. <span>“Lee–Carter Mortality Forecasting with Age-Specific Enhancement.”</span> <em>Insurance: Mathematics and Economics</em> 33 (2): 255–72.
</div>
<div id="ref-tuljapurkar2000" class="csl-entry" role="listitem">
Tuljapurkar, Shripad, Nan Li, and Carl Boe. 2000. <span>“A Universal Pattern of Mortality Decline in the G7 Countries.”</span> <em>Nature</em> 405 (6788): 789–92.
</div>
</div>
</section><section class="section level2"><h2 id="see-also">See also<a class="anchor" aria-label="anchor" href="#see-also"></a>
</h2>
<div class="justify">
<p>For more similar mortality datasets, see <a href="https://dutangc.github.io/CASdatasets/reference/fremorttables.html" class="external-link"><code>freMortTables</code></a> : French mortality datasets or visit the <a href="www.mortality.org">HMD</a> website.</p>
</div>
</section><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config);
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="http://dutangc.free.fr" class="external-link">Christophe Dutang</a>, <a href="https://freakonometrics.github.io" class="external-link">Arthur Charpentier</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.1.</p>
</div>

    </footer>
</div>





  </body>
</html>
