<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Claims reserving of a French Motor Third Party Liability triangle dataset • CASdatasets</title>
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.4.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="triangle_vignette_files/libs/quarto-html/popper.min.js"></script><script src="triangle_vignette_files/libs/quarto-html/tippy.umd.min.js"></script><link href="triangle_vignette_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="triangle_vignette_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link rel="stylesheet" href="style.scss">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Claims reserving of a French Motor Third Party Liability triangle dataset">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">CASdatasets</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">1.2-0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../articles/CASdatasets.html">Get started</a></li>
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles">
<li><a class="dropdown-item" href="../articles/poisson_vignette.html">Frequency analysis of a French Motor Third Party Liability dataset</a></li>
    <li><a class="dropdown-item" href="../articles/quasi_poisson_vignette_ausprivauto0405.html">Frequency analysis of an Australian Motor Third Party Liability dataset</a></li>
    <li><a class="dropdown-item" href="../articles/zero_inflated_vignette.html">Frequency analysis of a Norwegian Motor Third Party Liability dataset</a></li>
    <li><a class="dropdown-item" href="../articles/gam_rc_phileas_vignette.html">Frequency analysis of a Belgian Motor Third Party Liability dataset</a></li>
    <li><a class="dropdown-item" href="../articles/triangle_vignette.html">Claims reserving of a French Motor Third Party Liability triangle dataset</a></li>
    <li><a class="dropdown-item" href="../articles/triangle_aids_vignette.html">Reserving exercice on reporting delays in AIDS Data</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/dutangc/CASdatasets/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">

      <h1>Claims reserving of a French Motor Third Party Liability triangle dataset</h1>

      <p class="author">Julien Siharath</p>
      <p class="date">August, 2024</p>

      <small class="dont-index">Source: <a href="https://github.com/dutangc/CASdatasets/blob/master/vignettes/triangle_vignette.qmd" class="external-link"><code>vignettes/triangle_vignette.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <section class="section level2"><h2 id="sec-triangles-introduction">Introduction<a class="anchor" aria-label="anchor" href="#sec-triangles-introduction"></a>
</h2>
<div class="cell">
<details class="code-fold"><summary>Session Settings</summary><div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Graphs----</span></span>
<span><span class="va">face_text</span><span class="op">=</span><span class="st">'plain'</span></span>
<span><span class="va">face_title</span><span class="op">=</span><span class="st">'plain'</span></span>
<span><span class="va">size_title</span> <span class="op">=</span> <span class="fl">14</span></span>
<span><span class="va">size_text</span> <span class="op">=</span> <span class="fl">11</span></span>
<span><span class="va">legend_size</span> <span class="op">=</span> <span class="fl">11</span></span></code></pre></div>
</details>
</div>
<div class="cell">
<style type="text/css">
.justify {
  text-align: justify !important
}
</style>
</div>
<div>
<blockquote>
<p><strong>In Brief</strong></p>
<p>The purpose of this vignette is to illustrate a reserving exercise aimed at forecasting future claims development, specifically focusing on the bottom right corner of the triangle and potential further developments. These estimates are essential for maintaining the financial stability of insurance companies and ensuring they can meet their future claim obligations. We will use the <code>fretri1auto9605</code> dataset from <span class="citation" data-cites="charpentierCAS">Charpentier (<a href="#ref-charpentierCAS" role="doc-biblioref">2014</a>)</span> and work with the <code>Chainladder</code> package.</p>
</blockquote>
</div>
<section class="level2"><h3 id="required-packages">Required Packages<a class="anchor" aria-label="anchor" href="#required-packages"></a>
</h3>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">required_libraries</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"tidyverse"</span>, </span>
<span>  <span class="st">"CASdatasets"</span>,</span>
<span>  <span class="st">"ChainLadder"</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/invisible.html" class="external-link">invisible</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html" class="external-link">lapply</a></span><span class="op">(</span><span class="va">required_libraries</span>, <span class="va">library</span>, character.only <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</details>
</div>
</section><section class="level2"><h3 id="data">Data<a class="anchor" aria-label="anchor" href="#data"></a>
</h3>
<div class="justify">
<p>The dataset <code>fretri1auto9605</code> comprises claim triangles for motor policies from a French non-life insurer spanning the years 1996 to 2005.</p>
<p>In this context, a triangle is a table used to display data over time. It shows information across two dimensions:</p>
<ul>
<li><p>Lines as origin Year: This is the year when the claim occurred.<br></p></li>
<li><p>Columns as development Year: This indicates the number of years that have passed since the origin year.<br></p></li>
</ul>
<p>The table helps to track and analyze how data evolves from the time of origin over subsequent years.</p>
<p><code>fretri1auto9605</code> includes the following elements:</p>
<ul>
<li>Damage guarantee<br>
</li>
<li>Body guarantee<br>
</li>
<li>Total<br>
</li>
</ul>
<p>Each element includes two types of triangles: paid claims and incurred claim amounts.</p>
<p>Here’s how they differ:</p>
<p>Paid Claims: These triangles display cumulative claim amounts. This means that for each development year, the amount shown includes all claims paid up to that point. As time progresses, the cumulative total increases or remains the same, never decreasing, as it reflects the ongoing addition of payments.</p>
<p>Incurred Claim Amounts: These triangles reflect the total estimated amount for claims that have occurred but are not necessarily paid yet. Unlike paid claims, the incurred amount is not cumulative. It represents the estimated total cost of claims for a specific development year, which can be adjusted based on new information or revisions. As such, the incurred amount can change over time, and it might not show a simple increasing trend.</p>
<p>We will focus on the triangle representing the paid damage claim amounts, which we will refer to as <code>Damage</code>.</p>
</div>
</section><section class="level2"><h3 id="dictionaries">Dictionaries<a class="anchor" aria-label="anchor" href="#dictionaries"></a>
</h3>
<p>The list of the 3 elements from the <code>fretri1auto9605</code> dataset is reported in <a href="#tbl-dict-fretri1auto9605" class="quarto-xref">Table 1</a>.</p>
<div class="justify">
<div id="tbl-dict-fretri1auto9605" class="striped hover quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dict-fretri1auto9605-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 1: Content of the <code>fretri1auto9605</code>
</figcaption><div aria-describedby="tbl-dict-fretri1auto9605-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table table-striped table-hover caption-top">
<thead><tr class="header">
<th>Elements</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>damage</td>
<td>Represents the damage guarantee for the insurance policy.</td>
</tr>
<tr class="even">
<td>body</td>
<td>Represents the body guarantee for the insurance policy.</td>
</tr>
<tr class="odd">
<td>total</td>
<td>Represents the total guarantee.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The list of the 2 triangles in each elements is reported in <a href="#tbl-dict-triangle" class="quarto-xref">Table 2</a>.</p>
<div id="tbl-dict-triangle" class="striped hover quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dict-triangle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 2: Content in each triangle
</figcaption><div aria-describedby="tbl-dict-triangle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table table-striped table-hover caption-top">
<colgroup>
<col style="width: 16%">
<col style="width: 83%">
</colgroup>
<thead><tr class="header">
<th>Triangle</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>paid</td>
<td>Shows the cumulative amount of claims paid up to each development period.</td>
</tr>
<tr class="even">
<td>incur</td>
<td>Represents the estimated total amount for claims that have occurred but are not necessarily paid yet.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</section><section class="level2"><h3 id="importation">Importation<a class="anchor" aria-label="anchor" href="#importation"></a>
</h3>
<div class="cell">
<details class="code-fold"><summary>Code for importing our dataset</summary><div class="sourceCode cell-code" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">fretri1auto9605</span><span class="op">)</span></span>
<span></span>
<span><span class="va">Damage</span> <span class="op">&lt;-</span> <span class="va">fretri1auto9605</span><span class="op">$</span><span class="va">damage</span><span class="op">$</span><span class="va">paid</span><span class="op">|&gt;</span></span>
<span>  <span class="fu">as.triangle</span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
</details>
</div>
</section></section><section class="section level2"><h2 id="sec-triangles-overview">Overview<a class="anchor" aria-label="anchor" href="#sec-triangles-overview"></a>
</h2>
<section class="level2"><h3 id="purpose">Purpose<a class="anchor" aria-label="anchor" href="#purpose"></a>
</h3>
<div class="justify">
<p>Unlike other industries, the insurance sector does not sell tangible products but rather promises. An insurance policy represents a commitment by the insurer to cover future claims in exchange for a premium paid upfront.</p>
<p>Consequently, insurers do not know the exact cost of their services in advance. Instead, they rely on historical data analysis and judgment to set a sustainable price for their offerings. In General Insurance (or Non-Life Insurance, such as motor, property, and casualty insurance), most policies are valid for a period of 12 months. However, the claims payment process can extend over several years or even decades. As a result, insurers often do not know the exact timing of when claims will be settled.</p>
<p>For example, after a major natural disaster like an earthquake, the sheer volume of claims can overwhelm an insurance company. Evaluating the damage to properties, businesses, and personal belongings can be a time-consuming process. Additionally, some claims may require detailed investigations to determine the extent of coverage and validate the legitimacy of the claims. In such cases, the settlements delay can be significant as insurers need time to thoroughly assess each claim and ensure accurate payouts.</p>
<p>To forecast future claims and manage pricing effectively, insurers use methods like chain ladder models. These models estimate future claims based on historical data and are crucial for anticipating upcoming challenges. We will showcase the ability of chain ladder models to provide forecasts, refine pricing strategies, and ensure resilience in a dynamic risk landscape. For additional details and insights on claims reserving, refer to <span class="citation" data-cites="gesmann2014claims">Gesmann (<a href="#ref-gesmann2014claims" role="doc-biblioref">2014</a>)</span>.</p>
</div>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-1-1">Data overview</a></li>
<li><a href="#tabset-1-2">Claims development chart</a></li>
<li><a href="#tabset-1-3">Origin year plot</a></li>
</ul>
<ul class="nav nav-tabs" id="NA" role="tablist"><li role="presentation" class="nav-item"><button data-bs-toggle="tab" data-bs-target="#NA" id="NA-tab" type="button" role="tab" aria-controls="NA" aria-selected="true" class="active nav-link">
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode cell-code" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html" class="external-link">print</a></span><span class="op">(</span><span class="va">Damage</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>      dev
origin         1        2        3        4        5        6        7        8
  1996        NA       NA       NA 139388.2 139619.7 139982.5 140052.8 139867.0
  1997        NA       NA 139650.2 140195.5 140315.7 140374.0 140411.0 140423.4
  1998        NA 136427.9 137736.1 138144.2 138219.5 138330.9 138413.8 138475.9
  1999  99741.09 136010.6 137524.4 138070.8 138303.9 138380.3 138486.1       NA
  2000 100206.10 127709.8 129251.7 129982.1 130291.3 130640.1       NA       NA
  2001 102502.50 133767.4 135024.4 135528.1 135956.1       NA       NA       NA
  2002  98919.46 125973.4 127334.7 127613.5       NA       NA       NA       NA
  2003  93163.87 118141.8 119127.6       NA       NA       NA       NA       NA
  2004  93283.37 117132.5       NA       NA       NA       NA       NA       NA
  2005  92422.10       NA       NA       NA       NA       NA       NA       NA
      dev
origin        9       10
  1996 139878.6 139904.6
  1997 140449.0       NA
  1998       NA       NA
  1999       NA       NA
  2000       NA       NA
  2001       NA       NA
  2002       NA       NA
  2003       NA       NA
  2004       NA       NA
  2005       NA       NA</code></pre>
</div>
</div>
</button></li></ul>
<div class="tab-content"><div class="active  tab-pane" id="NA" role="tabpanel" aria-labelledby="NA-tab">

<div id="tabset-1-2">
<div class="cell">
<details class="code-fold"><summary>Code to create the following graph</summary><div class="sourceCode cell-code" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">ChainLadder</span><span class="fu">::</span><span class="fu">plot</span><span class="op">(</span><span class="va">Damage</span><span class="op">/</span><span class="fl">1000</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div id="fig-dev-chart" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><div aria-describedby="fig-dev-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="triangle_vignette_files/figure-html/fig-dev-chart-1.png" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dev-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 1: Claims development chart of the damage triangle, with one line per origin period.
</figcaption></figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-3">
<div class="cell">
<details class="code-fold"><summary>Code to create the following graph</summary><div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">Damage</span><span class="op">/</span><span class="fl">1000</span>, lattice<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div id="fig-dev-origin" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><div aria-describedby="fig-dev-origin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="triangle_vignette_files/figure-html/fig-dev-origin-1.png" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dev-origin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 2: Claims development by origin year
</figcaption></figure>
</div>
</div>
</div>
</div>
</div></div>
</div>
</section></section><section class="section level2"><h2 id="mack-chain-ladder">Mack chain-ladder<a class="anchor" aria-label="anchor" href="#mack-chain-ladder"></a>
</h2>
<div class="justify">
<p>Thomas Mack published in <span class="citation" data-cites="Mack_distributionfree1993">Mack (<a href="#ref-Mack_distributionfree1993" role="doc-biblioref">1993</a>)</span> a method which estimates the standard errors of the chain-ladder forecast without assuming a distribution under three conditions.</p>
<p>Following the notation of <span class="citation" data-cites="Mack1999">Mack (<a href="#ref-Mack1999" role="doc-biblioref">1999</a>)</span> let <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>C</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><annotation encoding="application/x-tex">C_{ik}</annotation></semantics></math> denote the cumulative loss amounts of origin period (e.g., accident year) <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>i</mi><mo>=</mo><mn>1</mn><mo>,</mo><mi>…</mi><mo>,</mo><mi>m</mi></mrow><annotation encoding="application/x-tex">i=1,\ldots,m</annotation></semantics></math>, with losses known for development period (e.g., development year) <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>k</mi><mo>≤</mo><mi>n</mi><mo>+</mo><mn>1</mn><mo>−</mo><mi>i</mi><mi>.</mi></mrow><annotation encoding="application/x-tex">k \le n+1-i.</annotation></semantics></math></p>
<p>In order to forecast the amounts <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>C</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><annotation encoding="application/x-tex">C_{ik}</annotation></semantics></math> for <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>k</mi><mo>&gt;</mo><mi>n</mi><mo>+</mo><mn>1</mn><mo>−</mo><mi>i</mi></mrow><annotation encoding="application/x-tex">k &gt; n+1-i</annotation></semantics></math> the Mack chain-ladder-model assumes:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mtable><mtr><mtd columnalign="right" style="text-align: right"><mrow><mtext mathvariant="normal">CL1: </mtext><mspace width="0.333em"></mspace></mrow></mtd><mtd columnalign="left" style="text-align: left"><mi>E</mi><mrow><mo stretchy="true" form="prefix">[</mo><msub><mi>F</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><mo stretchy="false" form="prefix">|</mo><msub><mi>C</mi><mrow><mi>i</mi><mn>1</mn></mrow></msub><mo>,</mo><msub><mi>C</mi><mrow><mi>i</mi><mn>2</mn></mrow></msub><mo>,</mo><mi>…</mi><mo>,</mo><msub><mi>C</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><mo stretchy="true" form="postfix">]</mo></mrow><mo>=</mo><msub><mi>f</mi><mi>k</mi></msub><mrow><mspace width="0.333em"></mspace><mtext mathvariant="normal"> with </mtext><mspace width="0.333em"></mspace></mrow><msub><mi>F</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><mo>=</mo><mfrac><msub><mi>C</mi><mrow><mi>i</mi><mo>,</mo><mi>k</mi><mo>+</mo><mn>1</mn></mrow></msub><msub><mi>C</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub></mfrac></mtd></mtr><mtr><mtd columnalign="right" style="text-align: right"><mrow><mtext mathvariant="normal">CL2: </mtext><mspace width="0.333em"></mspace></mrow></mtd><mtd columnalign="left" style="text-align: left"><mi>V</mi><mi>a</mi><mi>r</mi><mrow><mo stretchy="true" form="prefix">(</mo><mfrac><msub><mi>C</mi><mrow><mi>i</mi><mo>,</mo><mi>k</mi><mo>+</mo><mn>1</mn></mrow></msub><msub><mi>C</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub></mfrac><mo stretchy="false" form="prefix">|</mo><msub><mi>C</mi><mrow><mi>i</mi><mn>1</mn></mrow></msub><mo>,</mo><msub><mi>C</mi><mrow><mi>i</mi><mn>2</mn></mrow></msub><mo>,</mo><mi>…</mi><mo>,</mo><msub><mi>C</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><mfrac><msubsup><mi>σ</mi><mi>k</mi><mn>2</mn></msubsup><mrow><msub><mi>w</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><msubsup><mi>C</mi><mrow><mi>i</mi><mi>k</mi></mrow><mi>α</mi></msubsup></mrow></mfrac></mtd></mtr><mtr><mtd columnalign="right" style="text-align: right"><mrow><mtext mathvariant="normal">CL3: </mtext><mspace width="0.333em"></mspace></mrow></mtd><mtd columnalign="left" style="text-align: left"><mo stretchy="false" form="prefix">{</mo><msub><mi>C</mi><mrow><mi>i</mi><mn>1</mn></mrow></msub><mo>,</mo><mi>…</mi><mo>,</mo><msub><mi>C</mi><mrow><mi>i</mi><mi>n</mi></mrow></msub><mo stretchy="false" form="postfix">}</mo><mo>,</mo><mo stretchy="false" form="prefix">{</mo><msub><mi>C</mi><mrow><mi>j</mi><mn>1</mn></mrow></msub><mo>,</mo><mi>…</mi><mo>,</mo><msub><mi>C</mi><mrow><mi>j</mi><mi>n</mi></mrow></msub><mo stretchy="false" form="postfix">}</mo><mo>,</mo><mrow><mspace width="0.333em"></mspace><mtext mathvariant="normal"> are independent for origin period </mtext><mspace width="0.333em"></mspace></mrow><mi>i</mi><mo>≠</mo><mi>j</mi></mtd></mtr></mtable><annotation encoding="application/x-tex">
\begin{aligned}
  \mbox{CL1: }  &amp; E[ F_{ik}| C_{i1},C_{i2},\ldots,C_{ik} ] = f_k
  \mbox{ with } F_{ik}=\frac{C_{i,k+1}}{C_{ik}}\\
    \mbox{CL2: } &amp;  Var( \frac{C_{i,k+1}}{C_{ik}} | C_{i1},C_{i2},
    \ldots,C_{ik} ) = \frac{\sigma_k^2}{w_{ik} C^\alpha_{ik}}\\
  \mbox{CL3: } &amp; \{C_{i1},\ldots,C_{in}\}, \{
    C_{j1},\ldots,C_{jn}\},\mbox{ are independent for origin period } i
    \neq j
\end{aligned}
</annotation></semantics></math></p>
<p>with <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>w</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><mo>∈</mo><mrow><mo stretchy="true" form="prefix">[</mo><mn>0</mn><mo>;</mo><mn>1</mn><mo stretchy="true" form="postfix">]</mo></mrow><mo>,</mo><mi>α</mi><mo>∈</mo><mo stretchy="false" form="prefix">{</mo><mn>0</mn><mo>,</mo><mn>1</mn><mo>,</mo><mn>2</mn><mo stretchy="false" form="postfix">}</mo></mrow><annotation encoding="application/x-tex">w_{ik} \in [0;1], \alpha \in \{0,1,2\}</annotation></semantics></math>. If these assumptions hold, the Mack chain-ladder-model gives an unbiased estimator for IBNR (Incurred But Not Reported) claims.</p>
<section class="level2"><h3 id="intuition-behind-the-method">Intuition Behind the Method<a class="anchor" aria-label="anchor" href="#intuition-behind-the-method"></a>
</h3>
<p>The Chain-Ladder model is used to project future claims based on historical data. The fundamental idea is that the pattern of claims development is relatively stable and predictable. The model assumes that the ratios of cumulative losses between successive development years remain consistent, allowing us to use these ratios to estimate future losses.</p>
<p><strong>Assumptions:</strong></p>
<ol type="1">
<li><p><strong>CL1: Expected Future Ratio</strong><br>
This assumption states that the expected future ratio <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>F</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><annotation encoding="application/x-tex">F_{ik}</annotation></semantics></math> of cumulative losses between successive development years is constant, given the known losses up to the current development year. In other words, the ratio of cumulative losses from one development year to the next is assumed to follow a consistent pattern, which can be summarized by a factor <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>f</mi><mi>k</mi></msub><annotation encoding="application/x-tex">f_k</annotation></semantics></math> that reflects this pattern.</p></li>
<li><p><strong>CL2: Variance of Future Ratio</strong><br>
This assumption specifies how the variance of the future ratio of cumulative losses behaves. It indicates that the variance is proportional to <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mfrac><msubsup><mi>σ</mi><mi>k</mi><mn>2</mn></msubsup><mrow><msub><mi>w</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><msubsup><mi>C</mi><mrow><mi>i</mi><mi>k</mi></mrow><mi>α</mi></msubsup></mrow></mfrac><annotation encoding="application/x-tex">\frac{\sigma_k^2}{w_{ik} C_{ik}^\alpha}</annotation></semantics></math>, where <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msubsup><mi>σ</mi><mi>k</mi><mn>2</mn></msubsup><annotation encoding="application/x-tex">\sigma_k^2</annotation></semantics></math> captures the variability, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>w</mi><mrow><mi>i</mi><mi>k</mi></mrow></msub><annotation encoding="application/x-tex">w_{ik}</annotation></semantics></math> is a weight, and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>α</mi><annotation encoding="application/x-tex">\alpha</annotation></semantics></math> is a parameter that adjusts for different levels of variance. This helps in quantifying the uncertainty around the forecasts.</p></li>
<li><p><strong>CL3: Independence of Origin Periods</strong><br>
This assumption ensures that the cumulative loss amounts from different origin periods are independent of each other. This means that the losses from one accident year do not affect the losses from another year, allowing for simpler and more robust estimation.</p></li>
</ol>
<p>The Mack Chain-Ladder model can be regarded as a weighted linear regression through the origin for each development period:</p>
<p>The Mack chain-ladder model can be regarded as a weighted linear regression through the origin for each development period: <code>lm(y ~ x  + 0, weights=w/x^(2-alpha))</code>, where <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>y</mi><annotation encoding="application/x-tex">y</annotation></semantics></math> is the vector of claims at development period <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>k</mi><mo>+</mo><mn>1</mn></mrow><annotation encoding="application/x-tex">k+1</annotation></semantics></math> and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>x</mi><annotation encoding="application/x-tex">x</annotation></semantics></math> is the vector of claims at development period <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>k</mi><annotation encoding="application/x-tex">k</annotation></semantics></math>.</p>
<p>The Mack method is implemented in the ChainLadder package via the function <code>MackChainLadder</code>.</p>
<p>As an example we apply the <code>MackChainLadder</code> function to our triangle <code>Damage</code>:</p>
</section>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mack</span> <span class="op">&lt;-</span> <span class="fu">MackChainLadder</span><span class="op">(</span><span class="va">Damage</span>, est.sigma<span class="op">=</span><span class="st">"Mack"</span><span class="op">)</span></span>
<span><span class="va">mack</span> <span class="co"># same as summary(mack) </span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MackChainLadder(Triangle = Damage, est.sigma = "Mack")

      Latest Dev.To.Date Ultimate      IBNR Mack.S.E CV(IBNR)
1996 139,905       1.000  139,905      0.00     0.00      NaN
1997 140,449       1.000  140,475     26.18     1.06   0.0405
1998 138,476       1.000  138,520     44.15    12.08   0.2736
1999 138,486       1.000  138,494      7.38   150.98  20.4724
2000 130,640       0.999  130,716     76.37   149.00   1.9510
2001 135,956       0.998  136,225    269.20   227.56   0.8453
2002 127,614       0.996  128,084    470.21   258.49   0.5497
2003 119,128       0.993  120,013    885.58   293.16   0.3310
2004 117,133       0.983  119,212  2,079.24   341.87   0.1644
2005  92,422       0.761  121,413 28,991.18 4,143.13   0.1429

                Totals
Latest:   1,280,207.64
Dev:              0.97
Ultimate: 1,313,057.12
IBNR:        32,849.48
Mack.S.E      4,227.78
CV(IBNR):         0.13</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Displaying the Mack model's parameters</span></span>
<span><span class="va">mack</span><span class="op">$</span><span class="va">f</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1.2907697 1.0102412 1.0037355 1.0017012 1.0013946 1.0005313 0.9997345
 [8] 1.0001324 1.0001864 1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Viewing the full triangle data from the Mack model</span></span>
<span><span class="va">mack</span><span class="op">$</span><span class="va">FullTriangle</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      dev
origin         1        2        3        4        5        6        7        8
  1996        NA       NA       NA 139388.2 139619.7 139982.5 140052.8 139867.0
  1997        NA       NA 139650.2 140195.5 140315.7 140374.0 140411.0 140423.4
  1998        NA 136427.9 137736.1 138144.2 138219.5 138330.9 138413.8 138475.9
  1999  99741.09 136010.6 137524.4 138070.8 138303.9 138380.3 138486.1 138449.4
  2000 100206.10 127709.8 129251.7 129982.1 130291.3 130640.1 130709.5 130674.8
  2001 102502.50 133767.4 135024.4 135528.1 135956.1 136145.7 136218.0 136181.9
  2002  98919.46 125973.4 127334.7 127613.5 127830.6 128008.9 128076.9 128042.9
  2003  93163.87 118141.8 119127.6 119572.6 119776.0 119943.1 120006.8 119974.9
  2004  93283.37 117132.5 118332.1 118774.1 118976.2 119142.1 119205.4 119173.8
  2005  92422.10 119295.6 120517.4 120967.6 121173.4 121342.3 121406.8 121374.6
      dev
origin        9       10
  1996 139878.6 139904.6
  1997 140449.0 140475.2
  1998 138494.2 138520.1
  1999 138467.7 138493.5
  2000 130692.1 130716.5
  2001 136199.9 136225.3
  2002 128059.9 128083.7
  2003 119990.8 120013.2
  2004 119189.6 119211.8
  2005 121390.7 121413.3</code></pre>
</div>
</div>
<div class="justify">
<p>The Mack model factors begin at 1.3 for the initial periods and gradually decrease to around 1 for the later periods. These factors represent the development factors for each period, indicating the expected growth in cumulative claims from one period to the next. This trend mirrors the typical pattern in insurance claims, where most claims are reported early in the development process, and the rate of increase slows down over time as claims stabilize.</p>
<p>The triangular data shows how claims develop over time for each origin period. For example, for the origin year 2005, claims start at 92422 in the 1st period and grow to 121413 by the 10th period. This pattern is essential for actuaries to predict future claims and set appropriate reserves.</p>
<p>Overall, this output provides a comprehensive view of how claims develop over time and the associated development factors used in the chain ladder method.</p>
</div>
</section><section class="section level2"><h2 id="sec-mack-graph">Graphs<a class="anchor" aria-label="anchor" href="#sec-mack-graph"></a>
</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-2-1">Model’s Plot</a></li>
<li><a href="#tabset-2-2">Lattice plot</a></li>
</ul>
<ul class="nav nav-tabs" id="NA" role="tablist"><li role="presentation" class="nav-item"><button data-bs-toggle="tab" data-bs-target="#NA" id="NA-tab" type="button" role="tab" aria-controls="NA" aria-selected="true" class="active nav-link">
<div>
<blockquote>
<p><strong>Pay Attention</strong></p>
<div class="justify">
<p>To check that Mack’s assumption are valid, review the residual plots, we should see no trends in either of them.</p>
</div>
</blockquote>
</div>
<div class="cell">
<details class="code-fold"><summary>Code to create the following graph</summary><div class="sourceCode cell-code" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">mack</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div id="fig-plot-Mack1" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><div aria-describedby="fig-plot-Mack1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="triangle_vignette_files/figure-html/fig-plot-Mack1-1.png" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-Mack1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 3: MackPlot
</figcaption></figure>
</div>
</div>
</div>
<p>There are no apparent trend so the model is valid.</p>
</button></li></ul>
<div class="tab-content"><div class="active  tab-pane" id="NA" role="tabpanel" aria-labelledby="NA-tab">

<div id="tabset-2-2">
<p>We can plot the development, including the forecast and estimated standard errors by origin period by setting the argument <code>lattice=TRUE</code>.</p>
<div class="cell">
<details class="code-fold"><summary>Code to create the following graph</summary><div class="sourceCode cell-code" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">mack</span>, lattice<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div id="fig-plot-Mack2" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig"><div aria-describedby="fig-plot-Mack2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="triangle_vignette_files/figure-html/fig-plot-Mack2-1.png" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-Mack2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 4: MackPlot Lattice
</figcaption></figure>
</div>
</div>
</div>
</div>
</div></div>
</div>
</section><section class="section level2"><h2 id="references">References<a class="anchor" aria-label="anchor" href="#references"></a>
</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-charpentierCAS" class="csl-entry" role="listitem">
Charpentier, Arthur. 2014. <em>Computational Actuarial Science with <span>R</span></em>. The <span>R</span> Series. CRC Press. <a href="https://www.routledge.com/Computational-Actuarial-Science-with-R/Charpentier/p/book/9781138033788" class="external-link">https://www.routledge.com/Computational-Actuarial-Science-with-R/Charpentier/p/book/9781138033788</a>.
</div>
<div id="ref-gesmann2014claims" class="csl-entry" role="listitem">
Gesmann, M. 2014. <span>“Claims Reserving and IBNR.”</span> In, edited by A. Charpentier. Chapman; Hall/CRC.
</div>
<div id="ref-Mack_distributionfree1993" class="csl-entry" role="listitem">
Mack, T. 1993. <span>“Distribution-Free Calculation of the Standard Error of Chain-Ladder Reserve Estimates.”</span> <em>ASTIN Bulletin</em> 23 (2): 213–25.
</div>
<div id="ref-Mack1999" class="csl-entry" role="listitem">
———. 1999. <span>“The Standard Error of Chain-Ladder Reserve Estimates: Recursive Calculation and Inclusion of a Tail-Factor.”</span> <em>ASTIN Bulletin</em> 29: 361–66.
</div>
</div>
</section><section class="section level2"><h2 id="see-also">See also<a class="anchor" aria-label="anchor" href="#see-also"></a>
</h2>
<div class="justify">
<p>For more similar triangles datasets, see <a href="https://dutangc.github.io/CASdatasets/reference/nortritpl.html" class="external-link"><code>nortritpl8800</code></a> (import with <code>data("ausprivauto0405")</code>): Australian liabilty insurance triangles dataset, <a href="https://dutangc.github.io/CASdatasets/reference/sgtriangles.html" class="external-link"><code>sgautoprop9701</code></a>: Singapore general liability triangles dataset (import with <code>data("norauto")</code>), <a href="https://dutangc.github.io/CASdatasets/reference/swtriangles.html" class="external-link"><code>swtri1auto</code></a>: Switzerland general liability triangles dataset (import with <code>data("beMTPL16")</code>), or <a href="https://dutangc.github.io/CASdatasets/reference/usautotri.html" class="external-link"><code>usautotri9504</code></a> (import with <code>data("pg17trainpol")</code>): US Automobile triangles dataset.</p>
</div>
</section><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'light-border',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config);
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by <a href="http://dutangc.free.fr" class="external-link">Christophe Dutang</a>, <a href="https://freakonometrics.github.io" class="external-link">Arthur Charpentier</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.0.</p>
</div>

    </footer>
</div>





  </body>
</html>
